import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Archive, Camera, ClipboardCheck, FileText, Filter, Plus, Search, Settings as SettingsIcon, SlidersHorizontal, WifiOff, X } from 'lucide-react';
import { useRegisterSW } from 'virtual:pwa-register/react';
import { Brand } from './components/Brand';
import { JournalFiltersPanel } from './components/JournalFilters';
import { Button, IconButton, Modal, Toast } from './components/ui';
import { applyDisplaySettings, defaultDisplaySettings, Settings } from './components/Settings';
import { db, initializeDatabase, nextNumber } from './db/database';
import { RecordEditor } from './features/RecordEditor';
import { matchesSearch } from './services/search';
import { createDefect, createInspection, createPhotoReport, type Defect, type Inspection, type ModuleKey, type PhotoReport } from './types/models';
import { isOverdue } from './services/validation';
import { applyJournalFilters, emptyFilters, type JournalFilters } from './services/filters';

type AnyRecord = Defect | Inspection | PhotoReport;
const modules: Array<{ key: ModuleKey; title: string; create: string; empty: string; latest: string; icon: typeof FileText }> = [
  { key: 'defects', title: 'Замечания', create: 'Новое замечание', empty: 'Замечаний пока нет', latest: 'Последние замечания', icon: FileText },
  { key: 'inspections', title: 'Проверка', create: 'Новая проверка', empty: 'Проверок пока нет', latest: 'Последние проверки', icon: ClipboardCheck },
  { key: 'photoReports', title: 'Фотоотчёт', create: 'Новый фотоотчёт', empty: 'Фотоотчётов пока нет', latest: 'Последние фотоотчёты', icon: Camera }
];

export function App() {
  const [ready, setReady] = useState(false); const [active, setActive] = useState(0); const [records, setRecords] = useState<Record<ModuleKey, AnyRecord[]>>({ defects: [], inspections: [], photoReports: [] }); const [editor, setEditor] = useState<AnyRecord>(); const [searchOpen, setSearchOpen] = useState(false); const [queries, setQueries] = useState<Record<ModuleKey, string>>({ defects: '', inspections: '', photoReports: '' }); const [filtersOpen, setFiltersOpen] = useState(false); const [statusFilter, setStatusFilter] = useState<Record<ModuleKey, string>>({ defects: '', inspections: '', photoReports: '' }); const [settingsOpen, setSettingsOpen] = useState(false); const [online, setOnline] = useState(navigator.onLine); const [toast, setToast] = useState(''); const scroll = useRef<Record<ModuleKey, number>>({ defects: 0, inspections: 0, photoReports: 0 }); const mainRef = useRef<HTMLDivElement>(null); const pagerRef = useRef<HTMLDivElement>(null); const swipe = useRef({ id: -1, x: 0, y: 0, time: 0, horizontal: false, dx: 0 });
  const [deleted, setDeleted] = useState<AnyRecord>();
  const [advancedFilters, setAdvancedFilters] = useState<Record<ModuleKey, JournalFilters>>({ defects: emptyFilters(), inspections: emptyFilters(), photoReports: emptyFilters() });
  const { needRefresh: [needRefresh], updateServiceWorker } = useRegisterSW();
  const load = useCallback(async () => { const [defects, inspections, photoReports] = await Promise.all([db.defects.orderBy('updatedAt').reverse().toArray(), db.inspections.orderBy('updatedAt').reverse().toArray(), db.photoReports.orderBy('updatedAt').reverse().toArray()]); setRecords({ defects, inspections, photoReports }); }, []);
  useEffect(() => { void initializeDatabase().then(async () => { const setting = await db.settings.get('display'); applyDisplaySettings({ ...defaultDisplaySettings, ...(setting?.value as object ?? {}) }); await load(); setReady(true); }).catch(error => { console.error(error); setToast('IndexedDB недоступна. Проверьте настройки браузера.'); setReady(true); }); }, [load]);
  useEffect(() => { const update = () => setOnline(navigator.onLine); addEventListener('online', update); addEventListener('offline', update); return () => { removeEventListener('online', update); removeEventListener('offline', update); }; }, []);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => { setToast(''); setDeleted(undefined); }, 4200); return () => clearTimeout(timer); }, [toast]);
  useEffect(() => registerWebMcp({ create: createRecord, search: (query: string) => setQueries(current => ({ ...current, [modules[active].key]: query })) }), [active]);

  function selectModule(index: number) { const currentKey = modules[active].key; if (mainRef.current) scroll.current[currentKey] = mainRef.current.scrollTop; setActive(Math.max(0, Math.min(2, index))); requestAnimationFrame(() => { if (mainRef.current) mainRef.current.scrollTop = scroll.current[modules[Math.max(0, Math.min(2, index))].key]; }); }
  async function createRecord() { const key = modules[active].key; const number = await nextNumber(key); const record = key === 'defects' ? createDefect(number) : key === 'inspections' ? createInspection(number) : createPhotoReport(number); if (record.type === 'defect') await db.defects.add(record); else if (record.type === 'inspection') await db.inspections.add(record); else await db.photoReports.add(record); await load(); setEditor(record); }
  async function deleteRecord(record: AnyRecord) { if (record.type === 'defect') await db.defects.delete(record.id); else if (record.type === 'inspection') await db.inspections.delete(record.id); else await db.photoReports.delete(record.id); setDeleted(record); setEditor(undefined); await load(); setToast(`${record.number} удалён`); }
  async function undoDelete() { if (!deleted) return; if (deleted.type === 'defect') await db.defects.put(deleted); else if (deleted.type === 'inspection') await db.inspections.put(deleted); else await db.photoReports.put(deleted); setDeleted(undefined); setToast('Удаление отменено'); await load(); }
  function onPointerDown(event: React.PointerEvent) { const target = event.target as HTMLElement; if (event.clientX < 24 || event.clientX > innerWidth - 24 || target.closest('input,textarea,select,button,a,[contenteditable=true],.horizontal-scroll,.report-photo__tools') || getSelection()?.toString()) return; swipe.current = { id: event.pointerId, x: event.clientX, y: event.clientY, time: performance.now(), horizontal: false, dx: 0 }; }
  function onPointerMove(event: React.PointerEvent) { const state = swipe.current; if (state.id !== event.pointerId) return; const dx = event.clientX - state.x, dy = event.clientY - state.y; if (!state.horizontal && Math.hypot(dx, dy) > 10) { if (Math.abs(dx) <= Math.abs(dy) * 1.3) { swipe.current.id = -1; return; } state.horizontal = true; event.currentTarget.setPointerCapture(event.pointerId); }
    if (!state.horizontal) return; state.dx = dx; const edge = (active === 0 && dx > 0) || (active === 2 && dx < 0); const shown = edge ? dx * .18 : dx; requestAnimationFrame(() => { if (pagerRef.current) { pagerRef.current.style.willChange = 'transform'; pagerRef.current.style.transform = `translate3d(${shown}px,0,0)`; } }); }
  function onPointerEnd(event: React.PointerEvent) { const state = swipe.current; if (state.id !== event.pointerId) return; swipe.current.id = -1; if (pagerRef.current) { pagerRef.current.style.transition = 'transform var(--motion-page) var(--ease-ios)'; pagerRef.current.style.transform = 'translate3d(0,0,0)'; setTimeout(() => { if (pagerRef.current) { pagerRef.current.style.transition = ''; pagerRef.current.style.willChange = ''; } }, 320); } if (!state.horizontal) return; const velocity = Math.abs(state.dx) / Math.max(1, performance.now() - state.time); if (Math.abs(state.dx) >= innerWidth * .22 || (velocity > .48 && Math.abs(state.dx) >= 18)) selectModule(active + (state.dx < 0 ? 1 : -1)); }
  if (!ready) return <div className="splash"><Brand /><span>Подготовка локальной базы…</span></div>;
  const key = modules[active].key; const query = queries[key]; const items = applyJournalFilters(records[key].filter(record => matchesSearch(record, query)).filter(record => !statusFilter[key] || ('status' in record && record.status === statusFilter[key]) || ('result' in record && record.result === statusFilter[key])), advancedFilters[key]);
  if (editor) return <RecordEditor initial={editor} onClose={() => { setEditor(undefined); void load(); }} onSaved={load} onDelete={deleteRecord} />;
  const EmptyIcon = modules[active].icon;
  return <div className="app-shell"><header className="topbar"><Brand /><div className="topbar__actions">{!online && <span className="offline"><WifiOff />Офлайн</span>}<IconButton label="Поиск по текущему модулю" onClick={() => setSearchOpen(value => !value)}><Search /></IconButton><IconButton label="Настройки" onClick={() => setSettingsOpen(true)}><SettingsIcon /></IconButton></div></header>
    <nav className="module-tabs" role="tablist" aria-label="Рабочие модули" onKeyDown={event => { if (event.key === 'ArrowRight') selectModule(active + 1); if (event.key === 'ArrowLeft') selectModule(active - 1); }}>{modules.map((module, index) => <button key={module.key} role="tab" aria-selected={active === index} className={active === index ? 'active' : ''} onClick={() => selectModule(index)}>{module.title}</button>)}</nav>
    {searchOpen && <div className="searchbar"><Search /><input autoFocus value={query} onChange={e => setQueries({ ...queries, [key]: e.target.value })} placeholder="Номер, объект, подрядчик, описание" aria-label="Поиск по текущему модулю" /><IconButton label="Очистить поиск" onClick={() => setQueries({ ...queries, [key]: '' })}><X /></IconButton></div>}
    <div ref={mainRef} className="main-scroll"><div ref={pagerRef} className="pager" onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={onPointerEnd} onPointerCancel={onPointerEnd}><main className="module-panel" role="tabpanel"><button className="create-card" onClick={() => void createRecord()}><span><Plus /><b>{modules[active].create}</b></span><small>Создать рабочую карточку</small></button><div className="journal-heading"><div><span>ЖУРНАЛ</span><h1>{modules[active].latest}</h1></div><IconButton label="Фильтры и сортировка" onClick={() => setFiltersOpen(true)}><Filter /></IconButton></div>{statusFilter[key] && <div className="chips"><button onClick={() => setStatusFilter({ ...statusFilter, [key]: '' })}>{statusFilter[key]} <X /></button></div>}{items.length ? <div className="record-list">{items.map(record => <RecordCard key={record.id} record={record} onClick={() => setEditor(record)} />)}</div> : <div className="empty-state"><EmptyIcon /><h2>{query || statusFilter[key] ? 'По заданным условиям ничего не найдено' : modules[active].empty}</h2><p>{query || statusFilter[key] ? 'Измените поиск или сбросьте фильтры.' : `Создайте ${modules[active].create.toLocaleLowerCase('ru')}, чтобы запись появилась в журнале.`}</p><Button variant="primary" onClick={() => query || statusFilter[key] ? (setQueries({ ...queries, [key]: '' }), setStatusFilter({ ...statusFilter, [key]: '' })) : void createRecord()}>{query || statusFilter[key] ? 'Сбросить условия' : modules[active].create}</Button></div>}</main></div></div>
    <div className="page-dots" aria-hidden="true">{modules.map((_, i) => <span className={i === active ? 'active' : ''} key={i} />)}</div>
    <Modal open={filtersOpen} title="Фильтры и сортировка" onClose={() => setFiltersOpen(false)}><div className="filter-options"><div className="status-filter"><button className={!statusFilter[key] ? 'active' : ''} onClick={() => setStatusFilter({ ...statusFilter, [key]: '' })}>Все статусы</button>{(key === 'defects' ? ['Черновик', 'Выдано', 'В работе', 'На проверке', 'Устранено', 'Закрыто', 'Архив'] : key === 'inspections' ? ['Принято', 'Принято с замечаниями', 'Не принято', 'Требуется повторное предъявление'] : []).map(value => <button key={value} className={statusFilter[key] === value ? 'active' : ''} onClick={() => setStatusFilter({ ...statusFilter, [key]: value })}>{value}</button>)}</div><JournalFiltersPanel module={key} value={advancedFilters[key]} onChange={value => setAdvancedFilters(current => ({ ...current, [key]: value }))} onDone={() => setFiltersOpen(false)} /><Button variant="ghost" onClick={() => { setStatusFilter({ ...statusFilter, [key]: '' }); setAdvancedFilters(current => ({ ...current, [key]: emptyFilters() })); }}><SlidersHorizontal />Сбросить все фильтры</Button></div></Modal>
    <Settings open={settingsOpen} onClose={() => setSettingsOpen(false)} onDataChanged={load} />
    {needRefresh && <Toast message="Доступно обновление" action="Обновить после сохранения" onAction={() => void updateServiceWorker(true)} />}{toast && <Toast message={toast} action={deleted ? 'Отменить' : undefined} onAction={deleted ? () => void undoDelete() : undefined} />}
  </div>;
}

function RecordCard({ record, onClick }: { record: AnyRecord; onClick: () => void }) {
  const module = record.type === 'defect' ? 'Замечание' : record.type === 'inspection' ? record.kind : 'Фотоотчёт'; const title = record.type === 'defect' ? record.description || 'Описание ещё не добавлено' : record.type === 'inspection' ? record.description || record.kind : record.title || 'Название ещё не добавлено'; const object = record.type === 'photoReport' ? `${record.photos.length} фото • ${record.photosPerPage} на листе` : `${record.object.gp ? `${record.object.gp} ГП` : 'Объект не выбран'}${record.object.name ? ` — ${record.object.name}` : ''}`; const status = record.type === 'defect' ? record.status : record.type === 'inspection' ? record.result : new Date(record.date).toLocaleDateString('ru-RU');
  return <button className="record-card" onClick={onClick}><div className="record-card__top"><b>{record.number}</b><span className={`status status--${statusTone(status)}`}>{record.type === 'defect' && isOverdue(record) ? 'Просрочено • ' : ''}{status}</span></div><span className="record-card__object">{object}</span><p>{title}</p><footer><span>{module}</span><span>›</span></footer></button>;
}
function statusTone(value: string) { if (/Закрыто|Устранено|Принято$/.test(value)) return 'success'; if (/Крит|Просроч|Не принято/.test(value)) return 'danger'; if (/проверке|замечаниями|повторное/.test(value)) return 'warning'; if (/Архив/.test(value)) return 'muted'; return 'primary'; }

function registerWebMcp(actions: { create: () => Promise<void>; search: (query: string) => void }) {
  const context = document.modelContext; if (!context?.registerTool) return;
  const lifecycle = new AbortController();
  try { void Promise.resolve(context.registerTool({ name: 'start_record_creation', title: 'Создать рабочую карточку', description: 'Открывает новую черновую карточку в активном модуле РосКапСтрой.', inputSchema: { type: 'object', properties: {}, additionalProperties: false }, annotations: { readOnlyHint: false, untrustedContentHint: false }, execute: async () => { await actions.create(); return { status: 'draft_created' }; } }, { signal: lifecycle.signal })).catch(console.error);
    void Promise.resolve(context.registerTool({ name: 'search_current_journal', title: 'Поиск по текущему журналу', description: 'Задаёт поисковый запрос только для открытого рабочего модуля.', inputSchema: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'], additionalProperties: false }, annotations: { readOnlyHint: true, untrustedContentHint: false }, execute: (input: unknown) => { if (!input || typeof input !== 'object' || typeof (input as { query?: unknown }).query !== 'string') throw new Error('Требуется строка query'); actions.search((input as { query: string }).query); return { status: 'search_applied' }; } }, { signal: lifecycle.signal })).catch(console.error); } catch (error) { console.debug('WebMCP недоступен', error); }
  return () => lifecycle.abort();
}
