import {put,getAll,get,remove,exportAll,importAll} from './db.js';
import {defectPdf,checkPdf,photoReportPdf,saveBlob,blobSize} from './pdf.js';

const $ = (s,root=document)=>root.querySelector(s);
const $$ = (s,root=document)=>[...root.querySelectorAll(s)];
const esc = s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid = ()=>crypto.randomUUID?.() || `id-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const today = ()=>new Date().toISOString().slice(0,10);
const formatDate = d=>{if(!d)return '—'; const [y,m,day]=d.split('-'); return `${day}.${m}.${y}`};
const icons={
  search:'<path d="m21 21-4.3-4.3M10.8 18a7.2 7.2 0 1 1 0-14.4 7.2 7.2 0 0 1 0 14.4Z"/>',
  settings:'<path d="M12 15.2a3.2 3.2 0 1 0 0-6.4 3.2 3.2 0 0 0 0 6.4Z"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.87l.06.06-2.83 2.83-.06-.06A1.7 1.7 0 0 0 15 19.36a1.7 1.7 0 0 0-1 .64 1.7 1.7 0 0 0-.4 1.1V21h-4v-.1A1.7 1.7 0 0 0 8.5 19.3a1.7 1.7 0 0 0-1.87.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 4.14 15a1.7 1.7 0 0 0-.64-1 1.7 1.7 0 0 0-1.1-.4H2.3v-4h.1A1.7 1.7 0 0 0 4 8.5a1.7 1.7 0 0 0-.34-1.87l-.06-.06 2.83-2.83.06.06A1.7 1.7 0 0 0 8.36 4.14a1.7 1.7 0 0 0 1-.64 1.7 1.7 0 0 0 .4-1.1V2.3h4v.1A1.7 1.7 0 0 0 15 4a1.7 1.7 0 0 0 1.87-.34l.06-.06 2.83 2.83-.06.06A1.7 1.7 0 0 0 19.36 8.5c.15.37.37.7.64 1 .3.3.68.45 1.1.45h.1v4h-.1c-.42 0-.8.15-1.1.45-.27.3-.49.63-.64 1Z"/>',
  back:'<path d="m15 18-6-6 6-6"/>',more:'<circle cx="5" cy="12" r="1" fill="currentColor" stroke="none"/><circle cx="12" cy="12" r="1" fill="currentColor" stroke="none"/><circle cx="19" cy="12" r="1" fill="currentColor" stroke="none"/>',
  close:'<path d="m6 6 12 12M18 6 6 18"/>', camera:'<path d="M14.5 4 16 6h3a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h3l1.5-2h5Z"/><circle cx="12" cy="13" r="4"/>', image:'<rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="8.5" cy="9" r="1.5"/><path d="m21 15-5-5L5 20"/>'
};
const icon=n=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${icons[n]}</svg>`;

const sections=[
  ['ЭМ','Силовое электрооборудование и электроосвещение'],['ЭС','Электроснабжение'],['ЭО','Электроосвещение'],['ЭГ','Заземление и молниезащита'],['СС','Слаботочные системы'],['АПС','Автоматическая пожарная сигнализация'],['СОУЭ','Система оповещения и управления эвакуацией'],['СКУД','Система контроля и управления доступом'],['СВН','Система видеонаблюдения'],['АТХ','Автоматизация технологических процессов'],['АК','Автоматизация и контроль'],['ПНР','Пусконаладочные работы'],['ИД','Исполнительная документация']
];
const defectTypes=['Несоответствие РД','Нарушение НТД','Некачественный монтаж','Отсутствие маркировки','Нарушение заземления','Кабельные линии','Нарушение пожарной безопасности','Нарушение требований взрывозащиты','Неполнота документации','Повреждение','Несогласованное отклонение','Другое'];
const statuses=['Черновик','Выдано','В работе','На проверке','Устранено','Закрыто'];
const checkTypes=['Операционный контроль','Приёмочный контроль','Индивидуальные испытания','Комплексное опробование'];
const results=['Принято','Принято с замечаниями','Не принято','Требуется повторное предъявление'];
const defaultObjects=[{gp:'303',name:'Пересыпная станция №3'}];
const workTypes=['Монтаж кабельных линий','Монтаж электрооборудования','Монтаж заземления и молниезащиты','Монтаж слаботочных систем','Монтаж систем АПС/СОУЭ','Пусконаладочные работы','Индивидуальные испытания','Комплексное опробование','Исполнительная документация'];

const moduleConfig=[
  {key:'defects',title:'Замечания',journal:'Последние замечания',empty:'Замечаний пока нет',empty2:'Нажмите «Замечания», чтобы создать первую запись.'},
  {key:'photoRecords',title:'Проверка',journal:'Последние проверки',empty:'Проверок пока нет',empty2:'Нажмите «Проверка», чтобы создать первую запись.'},
  {key:'photoReports',title:'Фотоотчёт',journal:'Последние фотоотчёты',empty:'Фотоотчётов пока нет',empty2:'Нажмите «Фотоотчёт», чтобы создать первую запись.'}
];
const state={module:0,searchOpen:false,query:'',records:[[],[],[]],view:'home',editing:null,editingStore:null,settings:null,menu:false,saveTimer:null,photoTarget:null,pdf:null,pdfError:null,picker:null,gesture:null,scrolls:[0,0,0]};

function readSettings(){return {...{theme:'system',textScale:100,bold:false,contrast:false,bigButtons:false,objects:defaultObjects},...JSON.parse(localStorage.getItem('rks-settings')||'{}')}}
function applySettings(){const s=state.settings=readSettings();document.documentElement.dataset.theme=s.theme==='system'?'':s.theme;document.documentElement.style.setProperty('--text-scale',String(s.textScale/100));document.documentElement.style.setProperty('--tap-scale',s.bigButtons?'1.08':'1');document.documentElement.classList.toggle('bold-ui',!!s.bold);document.documentElement.classList.toggle('high-contrast',!!s.contrast)}
function saveSettings(s){localStorage.setItem('rks-settings',JSON.stringify(s));state.settings=s;applySettings()}
async function loadRecords(){for(let i=0;i<3;i++){state.records[i]=(await getAll(moduleConfig[i].key)).sort((a,b)=>(b.updatedAt||b.createdAt||'').localeCompare(a.updatedAt||a.createdAt||''))}}

async function nextNumber(store){const prefix=store==='defects'?'РКС':store==='photoRecords'?'ПРВ':'ФО';const rows=await getAll(store);let max=0;for(const r of rows){const m=String(r.number||'').match(/(\d+)$/);if(m)max=Math.max(max,Number(m[1]))}return `${prefix}-${String(max+1).padStart(6,'0')}`}
async function newRecord(index){
  const store=moduleConfig[index].key, number=await nextNumber(store), base={id:uid(),number,date:today(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};
  if(store==='defects') return {...base,status:'Черновик',gp:'',objectName:'',location:'',section:'',sectionCustom:'',workType:'',defectType:'',contractor:'',description:'',rd:'',ntd:[],instructions:'',dueDate:'',signDate:'',issuer:'Ведущий инженер ОСК Щипин С.А.',beforePhotos:[],afterPhotos:[]};
  if(store==='photoRecords') return {...base,checkType:'Операционный контроль',gp:'',objectName:'',description:'',result:'',details:{},scenario:[],photos:[]};
  return {...base,description:'',perPage:2,photos:[]};
}
function statusInfo(record,store){if(store==='defects' && record.dueDate && record.dueDate<today() && !['Устранено','Закрыто'].includes(record.status))return ['Просрочено','red'];const v=record.status||record.result||'Черновик';if(/Не принято|Просрочено/.test(v))return[v,'red'];if(/Устранено|Закрыто|Принято$/.test(v))return[v,'green'];if(/замечания|повторное/.test(v))return[v,'orange'];return[v,'blue']}
function firstPhoto(r,store){if(store==='defects')return r.beforePhotos?.[0]?.dataUrl;if(store==='photoRecords')return r.photos?.[0]?.dataUrl;return r.photos?.[0]?.dataUrl}
function recordTitle(r,store){if(store==='defects')return r.description||'Без описания';if(store==='photoRecords')return r.checkType||'Проверка';return r.description||'Фотоотчёт'}
function recordObject(r,store){if(store==='photoReports')return `${r.photos?.length||0} фото`;return [r.gp&&`${r.gp} ГП`,r.objectName].filter(Boolean).join(' · ')||'Объект не указан'}

function render(){
  const root=$('#app'); root.innerHTML=state.view==='home'?homeTemplate():state.view==='settings'?settingsTemplate():formTemplate();bind();
}
function brandSvg(){return `<svg viewBox="0 0 32 32" aria-hidden="true"><path d="M16 2.6 27 6.7v8.8c0 7.8-4.4 13.2-11 16.8C9.4 28.7 5 23.3 5 15.5V6.7L16 2.6Z" fill="#071F3D"/><path d="M10.5 19h11M12.2 15.5h7.6M14 12h4" stroke="#fff" stroke-width="2" stroke-linecap="round"/></svg>`}
function homeTemplate(){return `<main class="app-shell">
  <header class="topbar"><div class="brand">${brandSvg()}<span>РосКапСтрой</span></div><div class="top-actions"><button class="icon-btn" id="searchBtn" aria-label="Поиск">${icon('search')}</button><button class="icon-btn" id="settingsBtn" aria-label="Настройки">${icon('settings')}</button></div></header>
  ${state.searchOpen?`<div class="search-panel"><div class="search-wrap">${icon('search')}<input id="globalSearch" value="${esc(state.query)}" placeholder="Номер, объект, подрядчик, описание" aria-label="Поиск по текущему модулю"></div></div>`:''}
  <div class="viewport" id="viewport" tabindex="0" aria-label="Рабочие модули"><div class="track" id="track" style="transform:translate3d(${-state.module*33.333333}%,0,0)">${moduleConfig.map((m,i)=>modulePage(m,i)).join('')}</div></div>
  ${state.pdf?pdfReadyTemplate():''}${state.pdfError?errorTemplate():''}${state.menu?homeMenuTemplate():''}
</main>`}
function modulePage(m,i){const q=state.query.trim().toLowerCase();const rows=state.records[i].filter(r=>!q||JSON.stringify(r).toLowerCase().includes(q));return `<section class="module-page" data-module="${i}"><div class="module-card" data-create="${i}" role="button" tabindex="0" aria-label="Создать: ${m.title}"><h1>${m.title}</h1><span class="chev">›</span></div><div class="pager-hint"><span>Свайп влево / вправо</span><div class="dots">${moduleConfig.map((_,d)=>`<span class="dot ${d===i?'active':''}"></span>`).join('')}</div></div><div class="journal-head"><div class="eyebrow">ЖУРНАЛ</div><h2>${m.journal}</h2></div><div class="journal-list">${rows.length?rows.map(r=>recordCard(r,m.key)).join(''):`<div class="empty"><strong>${m.empty}</strong>${m.empty2}</div>`}</div></section>`}
function recordCard(r,store){const [status,cls]=statusInfo(r,store),photo=firstPhoto(r,store);return `<article class="record-card" data-open="${esc(r.id)}" data-store="${store}" tabindex="0">${photo?`<img class="thumb" src="${photo}" alt="Фото записи">`:''}<div class="record-body"><div class="record-top"><span class="record-id">${esc(r.number)}</span><span class="status ${cls}">${esc(status)}</span></div><div class="record-object">${esc(recordObject(r,store))}</div><div class="record-desc">${esc(recordTitle(r,store))}</div><div class="record-bottom"><span>${store==='defects'?`${esc(r.section||'—')} • ${r.dueDate?'Срок '+formatDate(r.dueDate):formatDate(r.date)}`:formatDate(r.date)}</span><span>›</span></div></div></article>`}
function homeMenuTemplate(){return `<div class="menu" id="homeMenu"><button id="exportBtn">Экспорт всех карточек</button><button id="importBtn">Импорт всех карточек</button></div>`}

function formTemplate(){const r=state.editing,store=state.editingStore;return `<main class="app-shell"><div class="sheet" style="max-height:none;min-height:100dvh;border-radius:0"><div class="form-toolbar"><button class="icon-btn" id="backBtn" aria-label="Назад">${icon('back')}</button><h2>${esc(r.number)}</h2><button class="toolbar-action" id="pdfBtn">PDF</button><button class="icon-btn" id="moreBtn" aria-label="Ещё">${icon('more')}</button>${state.menu?formMenuTemplate():''}</div><div class="form-content"><div class="save-state" id="saveState">Сохранено ✓</div>${store==='defects'?defectForm(r):store==='photoRecords'?checkForm(r):photoReportForm(r)}</div></div>${state.picker?workTypePickerTemplate():''}${state.pdf?pdfReadyTemplate():''}${state.pdfError?errorTemplate():''}</main>`}
function field(label,name,value='',type='text',attrs=''){return `<div class="field"><label for="${name}">${label}</label><input id="${name}" name="${name}" type="${type}" value="${esc(value)}" ${attrs}></div>`}
function selectField(label,name,value,options){return `<div class="field"><label for="${name}">${label}</label><select id="${name}" name="${name}">${options.map(o=>`<option ${o===value?'selected':''}>${esc(o)}</option>`).join('')}</select></div>`}
function textarea(label,name,value='',placeholder=''){return `<div class="field"><label for="${name}">${label}</label><textarea id="${name}" name="${name}" placeholder="${esc(placeholder)}">${esc(value)}</textarea></div>`}
function objectField(r){const q=(r.objectSearch??([r.gp,r.objectName].filter(Boolean).join(' — ')));return `<div class="field"><label for="objectSearch">Объект</label><input id="objectSearch" name="objectSearch" value="${esc(q)}" placeholder="№ ГП или название объекта" autocomplete="off"><div id="objectSuggestions"></div></div>`}
function photoSection(title,key,photos){return `<section class="section"><div class="section-title">${title}</div><div class="btn-row"><button class="btn" type="button" data-photo="camera" data-target="${key}">${icon('camera')} Сделать фото</button><button class="btn" type="button" data-photo="gallery" data-target="${key}">${icon('image')} Выбрать из галереи</button></div><div class="photo-grid" style="margin-top:10px">${(photos||[]).map((p,i)=>`<div class="photo-item"><img src="${p.dataUrl}" alt="Фото ${i+1}"><button class="photo-remove" data-remove-photo="${key}:${i}" type="button" aria-label="Удалить фото">×</button></div>`).join('')}</div></section>`}
function defectForm(r){return `<form id="recordForm"><section class="section"><div class="section-title">Документ</div><div class="grid-2">${field('Номер замечания','number',r.number)}${field('Дата','date',r.date,'date')}</div>${selectField('Статус','status',r.status,statuses)}</section><section class="section"><div class="section-title">Объект и работы</div>${objectField(r)}${field('Место / отметка / оборудование','location',r.location)}<div class="grid-2">${selectField('Раздел работ','section',r.section,['',...sections.map(s=>s[0]),'Другое'])}${field('Вид работ','workType',r.workType,'text','readonly data-worktype-picker="1" placeholder="Выбрать вид работ"')}</div>${r.section==='Другое'?field('Пользовательский раздел работ','sectionCustom',r.sectionCustom):''}${selectField('Тип недостатка','defectType',r.defectType,['',...defectTypes])}${field('Подрядчик','contractor',r.contractor)}</section>${photoSection('Фото недостатка','beforePhotos',r.beforePhotos)}<section class="section"><div class="section-title">Недостаток</div>${textarea('Описание недостатка','description',r.description,'Опишите выявленное несоответствие')}${field('Рабочая документация','rd',r.rd)}${ntdEditor(r.ntd)}${textarea('Указания по устранению','instructions',r.instructions,'Требования к исправлению')}</section><section class="section"><div class="section-title">Сроки и выдача</div><div class="grid-2">${field('Плановая дата устранения','dueDate',r.dueDate,'date')}${field('Дата подписания','signDate',r.signDate,'date')}</div>${field('Кем выдан документ','issuer',r.issuer)}</section>${photoSection('Фото после устранения','afterPhotos',r.afterPhotos)}<button class="btn primary" type="button" id="saveBtn">Сохранить</button></form>`}
function ntdEditor(rows=[]){return `<div class="field"><label>Нормативная документация</label><div id="ntdList">${rows.map((n,i)=>`<div class="ntd-row" data-ntd="${i}">${field('Название документа',`ntdName_${i}`,n.name)}${field('Пункт / пункты',`ntdClause_${i}`,n.clause)}<div class="row-actions"><button class="btn ghost" type="button" data-remove-ntd="${i}">Удалить</button></div></div>`).join('')}</div><button class="btn" type="button" id="addNtd">+ Добавить НТД</button></div>`}
function checkDetails(r){const d=r.details||{};const map={
  'Операционный контроль':[['Технологическая операция / этап','Технологическая операция / этап'],['Контролируемый параметр','Контролируемый параметр'],['Способ контроля','Способ контроля'],['Инструмент','Инструмент'],['Предшествующие работы','Предшествующие работы'],['Скрываемые работы','Скрываемые работы']],
  'Приёмочный контроль':[['Предъявленный объём','Предъявленный объём'],['Исполнительная документация','Исполнительная документация'],['Результаты испытаний','Результаты испытаний'],['Готовность следующего этапа','Готовность следующего этапа'],['Ранее выданные замечания','Ранее выданные замечания']],
  'Индивидуальные испытания':[['Оборудование / система','Оборудование / система'],['Заводской номер','Заводской номер'],['Программа / методика','Программа / методика'],['Прибор','Прибор'],['Номер прибора / поверка','Номер прибора / поверка'],['Нормативные параметры','Нормативные параметры'],['Фактический результат','Фактический результат']],
  'Комплексное опробование':[['Система','Система'],['Программа','Программа'],['Протокол','Протокол'],['Сценарий проверки','Сценарий проверки']]
};return (map[r.checkType]||[]).map(([key,label])=>field(label,`detail_${btoa(unescape(encodeURIComponent(key))).replace(/=/g,'')}`,d[key]||'','text',`data-detail="${esc(key)}"`)).join('')}
function scenarioEditor(rows=[]){return `<div class="field"><label>Шаги сценария</label><div id="scenarioList">${rows.map((s,i)=>`<div class="scenario-row" data-scenario="${i}">${field('Событие',`sc_event_${i}`,s.event)}${field('Команда',`sc_command_${i}`,s.command)}${field('Ожидаемый результат',`sc_expected_${i}`,s.expected)}${field('Фактический результат',`sc_actual_${i}`,s.actual)}${selectField('Статус',`sc_state_${i}`,s.state||'Выполнено',['Выполнено','Не выполнено','Не применяется'])}<div class="row-actions"><button class="btn ghost" type="button" data-remove-scenario="${i}">Удалить шаг</button></div></div>`).join('')}</div><button class="btn" type="button" id="addScenario">+ Добавить шаг</button></div>`}
function checkForm(r){return `<form id="recordForm"><section class="section"><div class="section-title">Проверка</div><div class="grid-2">${field('Номер','number',r.number)}${field('Дата','date',r.date,'date')}</div>${selectField('Вид контроля','checkType',r.checkType,checkTypes)}${objectField(r)}${textarea('Краткое описание','description',r.description)}</section><section class="section"><div class="section-title">Данные контроля</div><div id="detailsBlock">${checkDetails(r)}</div>${r.checkType==='Комплексное опробование'?scenarioEditor(r.scenario):''}${selectField('Результат проверки','result',r.result,['',...results])}</section>${photoSection('Фотографии проверки','photos',r.photos)}<button class="btn primary" type="button" id="saveBtn">Сохранить</button></form>`}
function photoReportForm(r){return `<form id="recordForm"><section class="section"><div class="section-title">Фотоотчёт</div>${textarea('Описание фотоотчёта','description',r.description,'Краткое описание выполненных работ / объекта')}${selectField('Количество фото на лист','perPage',String(r.perPage),['1','2','4','6'])}</section>${photoSection('Фотографии','photos',r.photos)}<div class="hint">PDF: A4 portrait, поля по 20 мм, изображения вписываются пропорционально без растягивания и автоматической обрезки.</div><div style="height:14px"></div><button class="btn primary" type="button" id="saveBtn">Сохранить</button></form>`}

function workTypePickerTemplate(){return `<div class="overlay"><div class="sheet"><div class="form-toolbar"><button class="icon-btn" id="closePicker" aria-label="Закрыть">${icon('close')}</button><h2>Вид работ</h2><span></span><span></span></div><div class="form-content"><div class="settings-list">${workTypes.map(v=>`<button class="setting-row" type="button" data-worktype-value="${esc(v)}"><strong>${esc(v)}</strong><span>›</span></button>`).join('')}</div><div class="divider"></div>${field('Свой вариант','customWorkType','')}<button class="btn primary" id="applyCustomWorkType" type="button">Использовать свой вариант</button></div></div></div>`}

function formMenuTemplate(){return `<div class="menu" style="z-index:20"><button id="duplicateBtn">Создать копию</button><button id="deleteBtn" style="color:var(--danger)">Удалить запись</button></div>`}

function settingsTemplate(){const s=state.settings;return `<main class="app-shell"><div class="sheet" style="max-height:none;min-height:100dvh;border-radius:0"><div class="form-toolbar"><button class="icon-btn" id="settingsBack" aria-label="Назад">${icon('back')}</button><h2>Настройки</h2><span></span><span></span></div><div class="form-content"><section class="section"><div class="section-title">Отображение</div><div class="setting-row"><div><strong>Размер текста</strong><small>${s.textScale}%</small></div><input id="textScale" type="range" min="80" max="140" step="10" value="${s.textScale}" style="width:150px"></div>${toggleRow('Жирный текст','bold',s.bold)}${toggleRow('Высокая контрастность','contrast',s.contrast)}${toggleRow('Увеличенные кнопки','bigButtons',s.bigButtons)}</section><section class="section"><div class="section-title">Тема</div>${selectField('Оформление','theme',s.theme,['system','light','dark']).replace('>system<','>Системная<').replace('>light<','>Светлая<').replace('>dark<','>Тёмная<')}</section><section class="section"><div class="section-title">Данные</div><div class="settings-list"><button class="btn" id="exportBtn">Экспорт всех карточек</button><button class="btn" id="importBtn">Импорт всех карточек</button><button class="btn" id="objectsBtn">Справочник объектов</button></div></section><section class="section"><div class="section-title">О приложении</div><div class="setting-row"><div><strong>РосКапСтрой</strong><small>Версия V1.8</small><small>Разработчик ПО · Святослав Щипин</small><a href="https://t.me/w40jvgg" target="_blank" rel="noopener">Telegram @w40jvgg</a></div></div></section></div></div>${state.menu?objectsTemplate():''}</main>`}
function toggleRow(label,key,on){return `<div class="setting-row"><div><strong>${label}</strong></div><button class="switch ${on?'on':''}" data-toggle="${key}" aria-pressed="${on}"></button></div>`}
function objectsTemplate(){return `<div class="overlay center"><div class="modal"><div class="form-toolbar"><button class="icon-btn" id="closeObjects">${icon('close')}</button><h2>Справочник объектов</h2><span></span><span></span></div><div class="form-content"><div id="objectsList">${(state.settings.objects||[]).map((o,i)=>`<div class="setting-row"><div><strong>${esc(o.gp)} — ${esc(o.name)}</strong></div><button class="btn ghost" data-remove-object="${i}">Удалить</button></div>`).join('')}</div><div class="grid-2" style="margin-top:14px">${field('№ ГП','newGp','')}${field('Наименование','newObjectName','')}</div><button class="btn primary" id="addObject">Добавить объект</button></div></div></div>`}
function pdfReadyTemplate(){return `<div class="overlay center"><div class="modal"><div class="pdf-ready"><div class="bigcheck">✓</div><h3>PDF готов</h3><p>${esc(state.pdf.name)} · ${blobSize(state.pdf.blob)}</p><div class="btn-row" style="justify-content:center"><button class="btn primary" id="savePdf">Сохранить PDF</button>${navigator.share?'<button class="btn" id="sharePdf">Поделиться</button>':''}<button class="btn" id="openPdf">Открыть документ</button><button class="btn ghost" id="closePdf">Закрыть</button></div></div></div></div>`}
function errorTemplate(){return `<div class="overlay center"><div class="modal"><div class="form-content"><h3>Не удалось сформировать PDF</h3><p class="hint">${esc(state.pdfError.message||String(state.pdfError))}</p><details><summary>Диагностика</summary><pre style="white-space:pre-wrap;font-size:11px">${esc(state.pdfError.stack||state.pdfError.message||String(state.pdfError))}</pre></details><button class="btn" id="closeError">Закрыть</button></div></div></div>`}

function bind(){
  $('#searchBtn')?.addEventListener('click',()=>{state.searchOpen=!state.searchOpen;render();setTimeout(()=>$('#globalSearch')?.focus(),0)});
  $('#settingsBtn')?.addEventListener('click',()=>{state.view='settings';render()});
  $('#globalSearch')?.addEventListener('input',e=>{state.query=e.target.value;render();setTimeout(()=>{const i=$('#globalSearch');if(i){i.focus();i.setSelectionRange(i.value.length,i.value.length)}},0)});
  $$('[data-create]').forEach(el=>{const go=()=>createAndEdit(Number(el.dataset.create));el.addEventListener('click',go);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go()}})});
  $$('[data-open]').forEach(el=>{const go=()=>openRecord(el.dataset.store,el.dataset.open);el.addEventListener('click',go);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go()}})});
  bindPager();
  $('#backBtn')?.addEventListener('click',saveAndBack);$('#settingsBack')?.addEventListener('click',()=>{state.view='home';render()});
  $('#moreBtn')?.addEventListener('click',()=>{state.menu=!state.menu;render()});
  $('#saveBtn')?.addEventListener('click',async()=>{syncForm();await commitRecord();toast('Сохранено ✓')});
  $('#deleteBtn')?.addEventListener('click',deleteCurrent);$('#duplicateBtn')?.addEventListener('click',duplicateCurrent);
  $('#pdfBtn')?.addEventListener('click',makePdf);
  bindForm();bindPhoto();bindSettings();bindImportExport();bindPdfDialog();
  document.addEventListener('focusin',focusFix,{once:true});
}
async function createAndEdit(i){state.module=i;state.editingStore=moduleConfig[i].key;state.editing=await newRecord(i);state.view='form';state.menu=false;render()}
async function openRecord(store,id){state.editingStore=store;state.editing=structuredClone(await get(store,id));state.view='form';state.menu=false;render()}
async function saveAndBack(){syncForm();await commitRecord();state.editing=null;state.editingStore=null;state.view='home';state.menu=false;await loadRecords();render()}
async function commitRecord(){if(!state.editing)return;state.editing.updatedAt=new Date().toISOString();await put(state.editingStore,state.editing);await put('drafts',{id:`${state.editingStore}:${state.editing.id}`,store:state.editingStore,record:state.editing,updatedAt:state.editing.updatedAt});await loadRecords()}
function scheduleDraft(){clearTimeout(state.saveTimer);const s=$('#saveState');if(s)s.textContent='Изменения…';state.saveTimer=setTimeout(async()=>{syncForm();if(state.editing){state.editing.updatedAt=new Date().toISOString();await put('drafts',{id:`${state.editingStore}:${state.editing.id}`,store:state.editingStore,record:state.editing,updatedAt:state.editing.updatedAt});const el=$('#saveState');if(el)el.textContent='Сохранено ✓'}},550)}
function syncForm(){const f=$('#recordForm');if(!f||!state.editing)return;const r=state.editing;for(const el of $$('input[name],textarea[name],select[name]',f)){if(el.name.startsWith('ntd')||el.name.startsWith('sc_')||el.dataset.detail)continue;r[el.name]=el.type==='number'?Number(el.value):el.value}if(state.editingStore==='defects'){r.ntd=$$('.ntd-row',f).map(row=>({name:$('input[name^="ntdName"]',row)?.value||'',clause:$('input[name^="ntdClause"]',row)?.value||''}))}if(state.editingStore==='photoRecords'){r.details={};$$('[data-detail]',f).forEach(el=>r.details[el.dataset.detail]=el.value);if(r.checkType==='Комплексное опробование')r.scenario=$$('.scenario-row',f).map(row=>({event:$('input[name^="sc_event"]',row)?.value||'',command:$('input[name^="sc_command"]',row)?.value||'',expected:$('input[name^="sc_expected"]',row)?.value||'',actual:$('input[name^="sc_actual"]',row)?.value||'',state:$('select[name^="sc_state"]',row)?.value||''}))}if(r.objectSearch){const match=(state.settings.objects||[]).find(o=>`${o.gp} — ${o.name}`===r.objectSearch);if(match){r.gp=match.gp;r.objectName=match.name}}
}
function bindForm(){const f=$('#recordForm');if(!f)return; $('[data-worktype-picker]')?.addEventListener('click',()=>{syncForm();state.picker='workType';render()}); $('#closePicker')?.addEventListener('click',()=>{state.picker=null;render()}); $$('[data-worktype-value]').forEach(b=>b.addEventListener('click',()=>{state.editing.workType=b.dataset.worktypeValue;state.picker=null;render();scheduleDraft()})); $('#applyCustomWorkType')?.addEventListener('click',()=>{const v=$('#customWorkType')?.value.trim();if(!v)return toast('Введите свой вид работ');state.editing.workType=v;state.picker=null;render();scheduleDraft()});f.addEventListener('input',e=>{if(e.target.id==='objectSearch')showObjectSuggestions(e.target.value);scheduleDraft()});f.addEventListener('change',e=>{if(e.target.name==='checkType'||e.target.name==='section'){syncForm();render();return}scheduleDraft()});$('#addNtd')?.addEventListener('click',()=>{syncForm();state.editing.ntd.push({name:'',clause:''});render()});$$('[data-remove-ntd]').forEach(b=>b.addEventListener('click',()=>{syncForm();state.editing.ntd.splice(Number(b.dataset.removeNtd),1);render()}));$('#addScenario')?.addEventListener('click',()=>{syncForm();state.editing.scenario.push({event:'',command:'',expected:'',actual:'',state:'Выполнено'});render()});$$('[data-remove-scenario]').forEach(b=>b.addEventListener('click',()=>{syncForm();state.editing.scenario.splice(Number(b.dataset.removeScenario),1);render()}))}
function showObjectSuggestions(q){const host=$('#objectSuggestions');if(!host)return;const needle=q.trim().toLowerCase();const rows=(state.settings.objects||[]).filter(o=>!needle||`${o.gp} ${o.name}`.toLowerCase().includes(needle)).slice(0,6);host.innerHTML=rows.length?`<div class="suggestions">${rows.map(o=>`<div class="suggestion" data-object="${esc(o.gp)}|||${esc(o.name)}">${esc(o.gp)} — ${esc(o.name)}</div>`).join('')}</div>`:'';$$('[data-object]',host).forEach(x=>x.addEventListener('click',()=>{const [gp,name]=x.dataset.object.split('|||');state.editing.gp=gp;state.editing.objectName=name;state.editing.objectSearch=`${gp} — ${name}`;render()}))}

function bindPhoto(){$$('[data-photo]').forEach(b=>b.addEventListener('click',()=>{syncForm();state.photoTarget=b.dataset.target;const input=b.dataset.photo==='camera'?$('#cameraInput'):$('#galleryInput');input.value='';input.click()}));$$('[data-remove-photo]').forEach(b=>b.addEventListener('click',()=>{const [key,idx]=b.dataset.removePhoto.split(':');state.editing[key].splice(Number(idx),1);scheduleDraft();render()}));}
async function onFiles(files){if(!state.photoTarget||!state.editing)return;const arr=[];for(const f of files){try{arr.push({id:uid(),name:f.name||'photo.jpg',dataUrl:await compressImage(f),createdAt:new Date().toISOString()})}catch(e){toast('Не удалось обработать одно из фото')}}state.editing[state.photoTarget]=[...(state.editing[state.photoTarget]||[]),...arr];await commitRecord();render()}
function compressImage(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)),w=Math.max(1,Math.round(img.naturalWidth*scale)),h=Math.max(1,Math.round(img.naturalHeight*scale)),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);URL.revokeObjectURL(url);resolve(c.toDataURL('image/jpeg',.88))};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Ошибка изображения'))};img.src=url})}
$('#cameraInput')?.addEventListener('change',e=>onFiles([...e.target.files]));$('#galleryInput')?.addEventListener('change',e=>onFiles([...e.target.files]));

function bindPager(){const vp=$('#viewport'),track=$('#track');if(!vp||!track)return;vp.addEventListener('keydown',e=>{if(e.key==='ArrowRight'&&state.module<2){state.module++;render()}else if(e.key==='ArrowLeft'&&state.module>0){state.module--;render()}});let raf=0;const setX=px=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>track.style.transform=`translate3d(${px}px,0,0)`)};vp.onpointerdown=e=>{if(e.target.closest('button,input,textarea,select,a,.record-card,.module-card'))return;state.gesture={id:e.pointerId,x:e.clientX,y:e.clientY,t:performance.now(),axis:null,dx:0};vp.setPointerCapture?.(e.pointerId);track.style.transition='none';track.style.willChange='transform'};vp.onpointermove=e=>{const g=state.gesture;if(!g||g.id!==e.pointerId)return;const dx=e.clientX-g.x,dy=e.clientY-g.y;g.dx=dx;if(!g.axis){if(Math.abs(dx)<6&&Math.abs(dy)<6)return;g.axis=Math.abs(dx)>Math.abs(dy)*1.12?'x':'y'}if(g.axis!=='x')return;e.preventDefault();const w=vp.clientWidth,base=-state.module*w;let move=dx;if((state.module===0&&dx>0)||(state.module===2&&dx<0))move*=.18;setX(base+move)};const end=e=>{const g=state.gesture;if(!g)return;const w=vp.clientWidth,dt=Math.max(1,performance.now()-g.t),v=g.dx/dt;let next=state.module;if(g.axis==='x'&&(Math.abs(g.dx)>w*.22||(Math.abs(v)>.48&&Math.abs(g.dx)>=18)))next=Math.max(0,Math.min(2,state.module+(g.dx<0?1:-1)));state.module=next;track.style.willChange='auto';track.style.transition=`transform ${Math.min(350,Math.max(220,Math.abs(g.dx)*.35+220))}ms var(--ease-ios)`;track.style.transform=`translate3d(${-next*w}px,0,0)`;state.gesture=null;setTimeout(()=>{if(track){track.style.transition='';track.style.transform=`translate3d(${-next*33.333333}%,0,0)`}},360)};vp.onpointerup=end;vp.onpointercancel=end}

async function makePdf(){syncForm();await commitRecord();const btn=$('#pdfBtn');if(btn){btn.disabled=true;btn.textContent='…'}try{let blob,name;if(state.editingStore==='defects'){blob=await defectPdf(state.editing);name=`${state.editing.number}.pdf`}else if(state.editingStore==='photoRecords'){blob=await checkPdf(state.editing);name=`${state.editing.number}.pdf`}else{blob=await photoReportPdf(state.editing);name=`${state.editing.number}.pdf`}state.pdf={blob,name};state.pdfError=null}catch(e){state.pdfError=e;state.pdf=null}render()}
function bindPdfDialog(){$('#savePdf')?.addEventListener('click',()=>saveBlob(state.pdf.blob,state.pdf.name));$('#openPdf')?.addEventListener('click',()=>window.open(URL.createObjectURL(state.pdf.blob),'_blank'));$('#sharePdf')?.addEventListener('click',async()=>{try{const file=new File([state.pdf.blob],state.pdf.name,{type:'application/pdf'});if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:state.pdf.name});else saveBlob(state.pdf.blob,state.pdf.name)}catch(e){if(e.name!=='AbortError')toast('Не удалось открыть системное меню') }});$('#closePdf')?.addEventListener('click',()=>{state.pdf=null;render()});$('#closeError')?.addEventListener('click',()=>{state.pdfError=null;render()})}
async function deleteCurrent(){if(!confirm(`Удалить ${state.editing?.number}?`))return;await remove(state.editingStore,state.editing.id);state.editing=null;state.view='home';state.menu=false;await loadRecords();render()}
async function duplicateCurrent(){syncForm();const clone=structuredClone(state.editing);clone.id=uid();clone.number=await nextNumber(state.editingStore);clone.createdAt=new Date().toISOString();clone.updatedAt=clone.createdAt;state.editing=clone;state.menu=false;await commitRecord();render();toast('Создана копия')}

function bindSettings(){$$('[data-toggle]').forEach(b=>b.addEventListener('click',()=>{const s=structuredClone(state.settings),k=b.dataset.toggle;s[k]=!s[k];saveSettings(s);render()}));$('#textScale')?.addEventListener('change',e=>{const s=structuredClone(state.settings);s.textScale=Number(e.target.value);saveSettings(s);render()});$('#theme')?.addEventListener('change',e=>{const map={'Системная':'system','Светлая':'light','Тёмная':'dark'};const s=structuredClone(state.settings);s.theme=map[e.target.value]||e.target.value;saveSettings(s);render()});$('#objectsBtn')?.addEventListener('click',()=>{state.menu=true;render()});$('#closeObjects')?.addEventListener('click',()=>{state.menu=false;render()});$('#addObject')?.addEventListener('click',()=>{const gp=$('#newGp').value.trim(),name=$('#newObjectName').value.trim();if(!gp||!name)return toast('Заполните № ГП и наименование');const s=structuredClone(state.settings);if(!s.objects.some(o=>o.gp===gp&&o.name===name))s.objects.push({gp,name});saveSettings(s);render()});$$('[data-remove-object]').forEach(b=>b.addEventListener('click',()=>{const s=structuredClone(state.settings);s.objects.splice(Number(b.dataset.removeObject),1);saveSettings(s);render()}))}
function bindImportExport(){$('#exportBtn')?.addEventListener('click',async()=>{const data=await exportAll();const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});saveBlob(blob,`roskapstroy-backup-${today()}.json`);toast('Резервная копия создана')});$('#importBtn')?.addEventListener('click',()=>{$('#importInput').value='';$('#importInput').click()})}
$('#importInput')?.addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{await importAll(JSON.parse(await f.text()));applySettings();await loadRecords();state.view='home';render();toast('Данные восстановлены')}catch(err){alert(`Не удалось импортировать резервную копию: ${err.message}`)}})

function focusFix(e){const t=e.target;if(!t.matches?.('input,textarea,select'))return;setTimeout(()=>t.scrollIntoView({behavior:'smooth',block:'center'}),260)}
function toast(text){const old=$('.toast');old?.remove();const el=document.createElement('div');el.className='toast';el.textContent=text;document.body.appendChild(el);setTimeout(()=>el.remove(),2400)}

async function init(){applySettings();await loadRecords();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});window.addEventListener('beforeunload',()=>{syncForm()})}
init();
