(()=>{
const DB='rks-control-v1', STORE='entries';let db,records=[],module='remarks',filter='all',query='',editing=null,draft=null,toastTimer;
const modules={remarks:{label:'Замечания',icon:'⚠',title:'Замечания',sub:'Фиксация несоответствий и контроль устранения.',add:'Создать замечание'},photos:{label:'Фотоотчёт',icon:'▧',title:'Фотоотчёты',sub:'Фотофиксация хода и результата работ на объекте.',add:'Создать фотоотчёт'},id:{label:'Проверка ИД',icon:'▤',title:'Проверка ИД',sub:'Выберите документ ИД, внесите замечания и сохраните их по порядку.',add:'Начать проверку ИД'}};
const idTemplates=['Общий журнал работ','Реестр исполнительной документации','Акт технической готовности (АТГ)','Ведомость смонтированного электрооборудования','Ведомость смонтированных технических средств автоматизации','Исполнительные схемы','Ведомость изменений и отступлений','Техническое решение','Журнал прокладки кабелей','Протокол измерения сопротивления изоляции','Протокол проверки цепи между заземлителями и заземляемыми элементами','Акт передачи в ПНР'];
const organizations=['ЭнергоСК','ИСЭ','ТЭК Мосэнерго','Откл'];
const RD_CATALOG=Array.isArray(window.RKS_RD_CATALOG)?window.RKS_RD_CATALOG:[];
const OBJECT_CATALOG=Array.isArray(window.RKS_OBJECT_CATALOG)?window.RKS_OBJECT_CATALOG:[];
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rdLookalikes={A:'А',B:'В',C:'С',E:'Е',H:'Н',K:'К',M:'М',O:'О',P:'Р',T:'Т',X:'Х'};
const canonicalSearch=s=>String(s||'').normalize('NFKC').toUpperCase().replace(/Ё/g,'Е').replace(/[ABCEHKMOPTX]/g,c=>rdLookalikes[c]||c).replace(/[^0-9A-ZА-Я.]/g,'');
const uid=()=>crypto.randomUUID?.()||`r${Date.now()}${Math.random().toString(16).slice(2)}`;const today=()=>new Date().toISOString().slice(0,10);const niceDate=s=>{if(!s)return 'Без даты';const d=new Date(`${s}T12:00:00`);return new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short',year:'numeric'}).format(d)};
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB,1);req.onupgradeneeded=()=>req.result.createObjectStore(STORE,{keyPath:'id'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function all(){return new Promise((resolve,reject)=>{const req=db.transaction(STORE).objectStore(STORE).getAll();req.onsuccess=()=>resolve(req.result||[]);req.onerror=()=>reject(req.error)})}
function put(r){return new Promise((resolve,reject)=>{const req=db.transaction(STORE,'readwrite').objectStore(STORE).put(r);req.onsuccess=()=>resolve();req.onerror=()=>reject(req.error)})}
function del(id){return new Promise((resolve,reject)=>{const req=db.transaction(STORE,'readwrite').objectStore(STORE).delete(id);req.onsuccess=()=>resolve();req.onerror=()=>reject(req.error)})}
function toast(s){const el=$('#toast');el.textContent=s;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2400)}
function moduleIcon(k){const paths={remarks:'<path d="M12 3 2.8 20h18.4L12 3Z"/><path d="M12 9v5m0 3h.01"/>',photos:'<rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="8" cy="9" r="1"/><path d="m3 17 6-5 4 3 3-3 5 5"/>',id:'<path d="M6 3h9l4 4v14H6z"/><path d="M14 3v5h5M9 12h7M9 16h7"/>'};return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[k]||''}</svg>`}
function setupNav(){const html=Object.entries(modules).map(([k,m])=>`<button class="nav-btn ${module===k?'active':''}" data-module="${k}" type="button"><span class="nav-icon">${moduleIcon(k)}</span><span>${m.label}</span></button>`).join('');$('#sideNav').innerHTML=html;$('#mobileNav').innerHTML=html;$('#moduleTabs').innerHTML=Object.entries(modules).map(([k,m])=>`<button class="tab ${module===k?'active':''}" role="tab" aria-selected="${module===k}" data-module="${k}">${m.label}</button>`).join('');document.querySelectorAll('[data-module]').forEach(b=>b.onclick=()=>setModule(b.dataset.module));$('#pageTitle').textContent=modules[module].title;$('#pageSub').textContent=modules[module].sub;$('#addText').textContent=modules[module].add;$('#addBtn').setAttribute('aria-label',modules[module].add);}
function setModule(k){module=k;filter='all';setupNav();render()}
function statusText(r){if(r.type==='remarks')return r.status||'Открыто';if(r.type==='photos')return 'Фотоотчёт';if(Array.isArray(r.sections)){if(r.sections.some(s=>s.enabled!==false&&(s.remarks||[]).some(n=>n.enabled!==false&&n.text?.trim())))return 'Есть замечания';if(r.conclusion||r.signerName)return 'Проверено';return 'В работе'}const vals=(r.docs||[]).map(d=>d.status);if(vals.some(x=>x==='return'))return 'Есть замечания';if(vals.some(x=>x==='missing'))return 'Не комплект';if(vals.some(x=>x==='clarify'))return 'Уточнение';if(vals.length&&vals.every(x=>x==='accepted'))return 'Проверено';return 'В работе'}
function badge(s){const c=s==='Устранено'||s==='Проверено'?'green':s==='Есть замечания'?'red':s==='Не комплект'||s==='Открыто'?'orange':s==='Уточнение'?'blue':'';return `<span class="badge ${c}">${esc(s)}</span>`}
function typeLabel(t){return modules[t]?.label||''}
function recordSearchText(r){return canonicalSearch([r.project,r.place,r.workingDoc,r.standard,r.description,r.remedy,r.contractor,...(r.docs||[]).flatMap(d=>[d.name,d.number,d.note]),...(r.sections||[]).flatMap(s=>[s.name,s.number,...(s.remarks||[]).map(n=>n.text)])].filter(Boolean).join(' '))}
function matches(r){if(r.type!==module)return false;const p=canonicalSearch($('#projectFilter').value),selectedObject=OBJECT_CATALOG.find(x=>canonicalSearch(x.label)===p);if(p&&!recordSearchText(r).includes(p)&&!(selectedObject&&canonicalSearch(r.project||'')===canonicalSearch(selectedObject.code)))return false;const s=statusText(r);if(filter==='open'&&['Устранено','Проверено'].includes(s))return false;if(filter==='done'&&!['Устранено','Проверено'].includes(s))return false;if(filter==='return'&&!['Есть замечания','Не комплект','Уточнение'].includes(s))return false;if(query&&!recordSearchText(r).includes(canonicalSearch(query)))return false;return true}
function summary(){const rs=records.filter(r=>r.type==='remarks'),ids=records.filter(r=>r.type==='id'),ps=records.filter(r=>r.type==='photos');const open=rs.filter(r=>r.status!=='Устранено').length,waiting=ids.filter(r=>statusText(r)!=='Проверено').length,pcount=ps.reduce((n,r)=>n+(r.photos||[]).length,0),idNotes=ids.reduce((n,r)=>n+(r.sections||[]).reduce((m,section)=>m+(section.enabled===false?0:(section.remarks||[]).filter(note=>note.enabled!==false&&note.text?.trim()).length),0),0);const data=module==='remarks'?[['Открытые замечания',open,'требуют контроля'],['Всего замечаний',rs.length,'в рабочем журнале']]:module==='photos'?[['Фотоотчёты',ps.length,'сохранено записей'],['Фотографии',pcount,'во всех отчётах']]:[['Комплекты в работе',waiting,'проверка не завершена'],['Замечания по ИД',idNotes,'записаны вручную']];$('#homeSummary').innerHTML=data.map(x=>`<div class="summary-card"><div class="summary-label">${x[0]}</div><div class="summary-value">${x[1]}</div><div class="summary-note">${x[2]}</div></div>`).join('')}

function projectOptions(){return [...new Set([...OBJECT_CATALOG.map(x=>x.label),...records.map(r=>r.project).filter(Boolean)])]}
function rankProjectMatches(raw,limit=8){const q=canonicalSearch(raw);if(!q)return[];const known=new Set(OBJECT_CATALOG.map(x=>x.label)),items=[...OBJECT_CATALOG,...[...new Set(records.map(r=>r.project).filter(Boolean))].filter(label=>!known.has(label)).map(label=>({label,code:'',name:label}))];return items.map(item=>{const code=canonicalSearch(item.code),name=canonicalSearch(item.name),label=canonicalSearch(item.label);const score=code===q?260:code.startsWith(q)?230:code.includes(q)?195:name===q?170:name.startsWith(q)?145:name.includes(q)?115:label.includes(q)?85:0;return{item,score}}).filter(x=>x.score).sort((a,b)=>b.score-a.score||String(a.item.code||'').localeCompare(String(b.item.code||''),'ru',{numeric:true})||a.item.label.localeCompare(b.item.label,'ru')).slice(0,limit)}
function rankRD(raw,limit=12,preferredSection=''){const q=canonicalSearch(raw);if(!q)return[];const preferred=canonicalSearch(preferredSection);return RD_CATALOG.map(item=>{const code=canonicalSearch(item.code),section=canonicalSearch(item.section);let score=code===q?140:code.startsWith(q)?120:section===q?105:code.includes(q)?90:section.startsWith(q)?75:section.includes(q)?55:0;if(preferred&&section===preferred)score+=25;return{item,score}}).filter(x=>x.score).sort((a,b)=>b.score-a.score||a.item.code.localeCompare(b.item.code,'ru',{numeric:true})).slice(0,limit)}
function hideSmartSuggestions(){const box=$('#smartSuggestions');box.classList.add('hidden');box.innerHTML='';$('#projectFilter').setAttribute('aria-expanded','false')}
function showSmartSuggestions(){const input=$('#projectFilter'),box=$('#smartSuggestions'),raw=input.value.trim();if(!raw){hideSmartSuggestions();return}const objects=rankProjectMatches(raw,8),codes=rankRD(raw);let html='';if(objects.length)html+=`<div class="smart-heading">Объекты · ${OBJECT_CATALOG.length} в справочнике</div>`+objects.map(({item})=>`<button type="button" role="option" class="smart-option" data-smart-value="${encodeURIComponent(item.label)}"><span>${esc(item.label)}</span><small>${item.code?`№ по ГП ${esc(item.code)}`:'Сохранённый объект'}</small></button>`).join('');if(codes.length)html+=`<div class="smart-heading">Шифры рабочей документации · ${RD_CATALOG.length} в справочнике</div>`+codes.map(({item})=>`<button type="button" role="option" class="smart-option" data-smart-value="${encodeURIComponent(item.code)}"><span>${esc(item.code)}</span><small>${esc(item.section||'РД')}</small></button>`).join('');if(!html)html='<div class="smart-empty">Совпадений в справочниках нет. Можно продолжить поиск по введённому тексту.</div>';box.innerHTML=html;box.classList.remove('hidden');input.setAttribute('aria-expanded','true');box.querySelectorAll('.smart-option').forEach(b=>{b.onpointerdown=e=>e.preventDefault();b.onclick=()=>{input.value=decodeURIComponent(b.dataset.smartValue);hideSmartSuggestions();render();input.focus()}})}
function bindSmartSearch(){const input=$('#projectFilter'),box=$('#smartSuggestions');input.oninput=()=>{render();showSmartSuggestions()};input.onfocus=()=>{if(input.value.trim())showSmartSuggestions()};input.onkeydown=e=>{const first=box.querySelector('.smart-option');if(e.key==='Escape'){hideSmartSuggestions();return}if(e.key==='ArrowDown'&&first){e.preventDefault();first.focus()}if(e.key==='Enter'&&!box.classList.contains('hidden')&&first){e.preventDefault();first.click()}};box.onkeydown=e=>{const items=[...box.querySelectorAll('.smart-option')],i=items.indexOf(document.activeElement);if(e.key==='ArrowDown'){e.preventDefault();items[Math.min(items.length-1,i+1)]?.focus()}else if(e.key==='ArrowUp'){e.preventDefault();if(i<=0)input.focus();else items[i-1].focus()}else if(e.key==='Escape'){hideSmartSuggestions();input.focus()}};input.onblur=()=>setTimeout(()=>{if(!box.contains(document.activeElement))hideSmartSuggestions()},150);document.addEventListener('pointerdown',e=>{if(!e.target.closest('.project-picker'))hideSmartSuggestions()})}
function bindMobileChrome(){
 const search=$('#mobileSearch'),settings=$('#mobileSettings'),shade=$('#searchShade'),input=$('#projectFilter'),clear=$('#clearSearch'),dialog=$('#settingsDialog');
 const update=()=>search.classList.toggle('has-query',!!input.value.trim());
 const closeSearch=()=>{document.body.classList.remove('search-open');shade.classList.add('hidden');search.setAttribute('aria-expanded','false');search.setAttribute('aria-label','Открыть поиск');hideSmartSuggestions()};
 const openSearch=()=>{document.body.classList.add('search-open');shade.classList.remove('hidden');search.setAttribute('aria-expanded','true');search.setAttribute('aria-label','Закрыть поиск');input.focus()};
 search.onclick=()=>document.body.classList.contains('search-open')?closeSearch():openSearch();
 shade.onclick=closeSearch;
 clear.onclick=()=>{input.value='';render();hideSmartSuggestions();update();input.focus()};
 input.addEventListener('input',update);
 input.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.classList.contains('search-open')){closeSearch();search.focus()}});
 $('#smartSuggestions').addEventListener('click',update);
 settings.onclick=()=>{closeSearch();dialog.showModal()};
 $('#desktopSettings').onclick=()=>dialog.showModal();
 $('#closeSettings').onclick=()=>dialog.close();
 $('#settingsExport').onclick=()=>{dialog.close();exportBackup()};
 $('#settingsImport').onclick=()=>{dialog.close();$('#restoreInput').click()};
 dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
 update();
}
function filters(){const defs=module==='remarks'?[['all','Все'],['open','Открытые'],['done','Устранённые']]:module==='id'?[['all','Все'],['open','В работе'],['return','С замечаниями'],['done','Проверенные']]:[['all','Все фотоотчёты']];$('#filterBar').innerHTML=defs.map(([v,n])=>`<button class="filter-btn ${filter===v?'active':''}" data-filter="${v}">${n}${v==='all'?` <span>${records.filter(r=>r.type===module).length}</span>`:''}</button>`).join('');document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()})}
function card(r){const s=statusText(r),pics=r.type==='remarks'?[...(r.before||[]),...(r.after||[])]:r.photos||[],pic=pics[0],activeNotes=(r.sections||[]).reduce((n,x)=>n+(x.enabled===false?0:(x.remarks||[]).filter(m=>m.enabled!==false&&m.text?.trim()).length),0);const main=r.type==='id'?`${(r.sections||[]).length} разделов · ${activeNotes} активных замечаний`:r.type==='remarks'?(r.description||'Описание не заполнено'):(r.description||`${pics.length} фотографий`);const title=r.type==='remarks'&&remarkNumberIsEnabled(r)&&String(r.number||'').trim()?`Замечание № ${String(r.number).trim()}`:r.title||r.reportTitle||`Запись от ${niceDate(r.date)}`;return `<article class="record-card" data-open="${esc(r.id)}" tabindex="0"><div class="card-head">${pic?`<img class="thumb" src="${pic}" alt="Фото">`:`<div class="thumb thumb-placeholder">${modules[r.type].icon}</div>`}<div class="card-copy"><h3 class="card-title">${esc(title)}</h3><div class="card-sub">${esc(r.project||'Объект не указан')}${r.place?` · ${esc(r.place)}`:''}</div><div class="card-sub">${esc(main)}</div></div><button class="card-menu" type="button" data-print="${esc(r.id)}" title="Печать / PDF" aria-label="Печать или PDF">⋯</button></div><div class="card-meta">${badge(s)}<span>${niceDate(r.date)}</span>${r.type==='remarks'&&r.due?`<span>Срок: ${niceDate(r.due)}</span>`:''}${r.type==='photos'?`<span>${pics.length} фото</span>`:''}<span class="spacer"></span><span>${typeLabel(r.type)}</span></div></article>`}
function render(){setupNav();summary();projectOptions();filters();let list=records.filter(matches).sort((a,b)=>(b.updated||'').localeCompare(a.updated||''));$('#recordList').innerHTML=list.length?list.map(card).join(''):`<div class="empty"><div class="empty-icon">${modules[module].icon}</div><h3>${filter==='all'?'Записей пока нет':'По этому фильтру записей нет'}</h3><p>${module==='id'?'Начните проверку ИД: выберите документ и внесите замечания вручную.':module==='remarks'?'Зафиксируйте замечание, добавьте фото и укажите требуемое устранение.':'Соберите фотографии в отдельный фотоотчёт по объекту.'}</p><button class="primary-btn" data-empty-add>＋ ${modules[module].add}</button></div>`;document.querySelectorAll('[data-open]').forEach(e=>{e.onclick=ev=>{if(ev.target.closest('[data-print]'))return;edit(e.dataset.open)};e.onkeydown=ev=>{if(ev.key==='Enter')edit(e.dataset.open)}});document.querySelectorAll('[data-print]').forEach(b=>b.onclick=async ev=>{ev.stopPropagation();const r=records.find(x=>x.id===b.dataset.print);if(r?.type==='remarks')await generateRemarkPdf(r);else if(r?.type==='photos')await generatePhotoReportPdf(r);else printRecord(b.dataset.print)});$('[data-empty-add]')?.addEventListener('click',()=>editor());}
function field(label,name,value='',type='text',placeholder='',full=false,required=false){return `<label class="field ${full?'full':''}"><span>${label}${required?' *':''}</span><input name="${name}" type="${type}" value="${esc(value)}" placeholder="${esc(placeholder)}" ${required?'required':''}></label>`}
function organizationField(value=''){const options=value&&!organizations.includes(value)?[value,...organizations]:organizations;return `<label class="field"><span>Ответственная организация</span><select name="contractor"><option value="" disabled ${value?'':'selected'}>Выберите организацию</option>${options.map(v=>`<option value="${esc(v)}" ${value===v?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`}
function photoLayoutField(value='2'){const selected=['1','2','4','6'].includes(String(value))?String(value):'2';return `<div class="photo-layout"><label><span>Фото на листе PDF</span><select name="perPage" data-photo-layout><option value="1" ${selected==='1'?'selected':''}>1 фото</option><option value="2" ${selected==='2'?'selected':''}>2 фото</option><option value="4" ${selected==='4'?'selected':''}>4 фото</option><option value="6" ${selected==='6'?'selected':''}>6 фото</option></select></label></div>`}
function area(label,name,value='',placeholder='',full=true){return `<label class="field ${full?'full':''}"><span>${label}</span><textarea name="${name}" placeholder="${esc(placeholder)}">${esc(value)}</textarea></label>`}
function baseFields(r,showPlace=true){return `<div class="field-grid"><label class="field form-project-picker"><span>Объект *</span><input id="formProject" name="project" type="text" value="${esc(r.project||'')}" placeholder="Название объекта или шифр РД" autocomplete="off" required role="combobox" aria-autocomplete="list" aria-controls="formProjectSuggestions" aria-expanded="false"><div id="formProjectSuggestions" class="form-smart-suggestions hidden" role="listbox" aria-label="Подходящие объекты и шифры"></div></label>${field('Дата','date',r.date||today(),'date')}${showPlace?field('Место / участок','place',r.place||'','text','Корпус, этаж, помещение',true):''}</div>`}
function showFormProjectSuggestions(input,box){const raw=input.value.trim();if(!raw){box.classList.add('hidden');box.innerHTML='';input.setAttribute('aria-expanded','false');return}const objects=rankProjectMatches(raw,8),codes=rankRD(raw,8);let html='';if(objects.length)html+=`<div class="smart-heading">Подходящие объекты</div>`+objects.map(({item})=>`<button type="button" role="option" class="smart-option" data-form-smart-value="${encodeURIComponent(item.label)}"><span>${esc(item.label)}</span><small>${item.code?`№ по ГП ${esc(item.code)}`:'Сохранённый объект'}</small></button>`).join('');if(codes.length)html+=`<div class="smart-heading">Шифры рабочей документации</div>`+codes.map(({item})=>`<button type="button" role="option" class="smart-option" data-form-smart-value="${encodeURIComponent(item.code)}"><span>${esc(item.code)}</span><small>${esc(item.section||'РД')}</small></button>`).join('');if(!html)html='<div class="smart-empty">Совпадений нет. Можно оставить введённый текст.</div>';box.innerHTML=html;box.classList.remove('hidden');input.setAttribute('aria-expanded','true');box.querySelectorAll('[data-form-smart-value]').forEach(b=>{b.onpointerdown=e=>e.preventDefault();b.onclick=()=>{input.value=decodeURIComponent(b.dataset.formSmartValue);box.classList.add('hidden');input.setAttribute('aria-expanded','false');input.focus()}})}
function bindFormProjectSearch(fields){const input=fields.querySelector('#formProject'),box=fields.querySelector('#formProjectSuggestions');if(!input||!box)return;input.oninput=()=>showFormProjectSuggestions(input,box);input.onfocus=()=>{if(input.value.trim())showFormProjectSuggestions(input,box)};input.onkeydown=e=>{const first=box.querySelector('[data-form-smart-value]');if(e.key==='Escape'){box.classList.add('hidden');input.setAttribute('aria-expanded','false')}else if(e.key==='ArrowDown'&&!box.classList.contains('hidden')&&first){e.preventDefault();first.focus()}else if(e.key==='Enter'&&!box.classList.contains('hidden')&&first){e.preventDefault();first.click()}};input.onblur=()=>setTimeout(()=>{if(!box.contains(document.activeElement)){box.classList.add('hidden');input.setAttribute('aria-expanded','false')}},150);box.onkeydown=e=>{const items=[...box.querySelectorAll('[data-form-smart-value]')],i=items.indexOf(document.activeElement);if(e.key==='ArrowDown'){e.preventDefault();items[Math.min(items.length-1,i+1)]?.focus()}else if(e.key==='ArrowUp'){e.preventDefault();if(i<=0)input.focus();else items[i-1].focus()}else if(e.key==='Escape'){box.classList.add('hidden');input.setAttribute('aria-expanded','false');input.focus()}}}
function bindFormRDSearch(fields){const input=fields.querySelector('#workingDocSearch'),box=fields.querySelector('#workingDocSuggestions');if(!input||!box)return;const close=()=>{box.classList.add('hidden');input.setAttribute('aria-expanded','false')};input.oninput=()=>{const raw=input.value.trim();if(!raw){close();box.innerHTML='';return}const matches=rankRD(raw,8);box.innerHTML=matches.length?'<div class="smart-heading">Подходящие разделы рабочей документации</div>'+matches.map(({item})=>`<button type="button" role="option" class="smart-option" data-rd-value="${encodeURIComponent(item.code)}"><span>${esc(item.code)}</span><small>${esc(item.section||'Раздел РД')}</small></button>`).join(''):'<div class="smart-empty">Совпадений по шифру или названию нет.</div>';box.classList.remove('hidden');input.setAttribute('aria-expanded','true');box.querySelectorAll('[data-rd-value]').forEach(b=>{b.onpointerdown=e=>e.preventDefault();b.onclick=()=>{input.value=decodeURIComponent(b.dataset.rdValue);close();input.focus()}})};input.onfocus=()=>{if(input.value.trim())input.oninput()};input.onkeydown=e=>{const first=box.querySelector('[data-rd-value]');if(e.key==='Escape')close();else if(e.key==='ArrowDown'&&!box.classList.contains('hidden')&&first){e.preventDefault();first.focus()}else if(e.key==='Enter'&&!box.classList.contains('hidden')&&first){e.preventDefault();first.click()}};input.onblur=()=>setTimeout(()=>{if(!box.contains(document.activeElement))close()},150);box.onkeydown=e=>{const items=[...box.querySelectorAll('[data-rd-value]')],i=items.indexOf(document.activeElement);if(e.key==='ArrowDown'){e.preventDefault();items[Math.min(items.length-1,i+1)]?.focus()}else if(e.key==='ArrowUp'){e.preventDefault();if(i<=0)input.focus();else items[i-1].focus()}else if(e.key==='Escape'){close();input.focus()}}}
function bindIdDocuments(fields){const sections=ensureSections(draft);fields.querySelectorAll('[data-open-section]').forEach(b=>b.onclick=()=>{captureDraft(draft);$('#workflowDialog').showModal();renderSection(+b.dataset.openSection)});$('#addIdDocument')?.addEventListener('click',()=>{const input=$('#newIdDocumentName'),name=input.value.trim();if(!name){toast('Введите название документа');input.focus();return}captureDraft(draft);sections.push(makeSection(name));paintEditor(draft);$('#newIdDocumentName')?.focus()});fields.querySelectorAll('[data-move-id-document]').forEach(b=>b.onclick=()=>{const i=+b.dataset.moveIdDocument,j=i+(+b.dataset.dir);if(j<0||j>=sections.length)return;captureDraft(draft);[sections[i],sections[j]]=[sections[j],sections[i]];paintEditor(draft)});fields.querySelectorAll('[data-delete-id-document]').forEach(b=>b.onclick=()=>{const i=+b.dataset.deleteIdDocument;if(confirm(`Удалить «${sections[i].name}» и внесённые к нему замечания?`)){captureDraft(draft);sections.splice(i,1);paintEditor(draft)}})}
function photoFields(r,key,label){const pics=r[key]||[];return `<div class="field full photo-group">${photoLayoutField(r.perPage||'2')}<span class="field-label">${label} · ${pics.length} фото</span><input class="photo-input" type="file" accept="image/*" capture="environment" multiple data-photos="${key}"><p class="hint">Фотографии сжимаются перед сохранением в журнал.</p><div class="photo-strip" data-strip="${key}">${pics.map((src,i)=>`<div class="photo-preview"><img src="${src}" alt="Фото ${i+1}"><button type="button" data-remove-photo="${key}" data-index="${i}" aria-label="Удалить">×</button></div>`).join('')}</div></div>`}
function remarkNumberIsEnabled(r){return r.numberEnabled===true||(r.numberEnabled===undefined&&!!String(r.number||'').trim())}
function nextRemarkNumber(){return String(1+Math.max(0,...records.filter(r=>r.type==='remarks'&&remarkNumberIsEnabled(r)&&/^\d+$/.test(String(r.number||''))).map(r=>Number(r.number))))}
function bindRemarkNumber(fields){const toggle=fields.querySelector('#remarkNumberEnabled'),input=fields.querySelector('#remarkNumber'),wrap=fields.querySelector('#remarkNumberWrap');if(!toggle||!input||!wrap)return;const update=()=>{wrap.classList.toggle('hidden',!toggle.checked);$('#formTitle').textContent=`${editing?'Изменить':'Создать'} замечание${toggle.checked&&input.value.trim()?` № ${input.value.trim()}`:''}`};toggle.addEventListener('change',update);input.addEventListener('input',update);update()}
function remarkForm(r){const numbered=remarkNumberIsEnabled(r);return `${baseFields(r)}<div class="field-grid remark-number-row"><label class="switch"><input id="remarkNumberEnabled" name="numberEnabled" type="checkbox" ${numbered?'checked':''}><span></span>Указывать номер замечания</label><label class="field ${numbered?'':'hidden'}" id="remarkNumberWrap"><span>Номер замечания</span><input id="remarkNumber" name="number" type="text" inputmode="numeric" value="${esc(r.number||'')}" placeholder="Например, 1"></label></div><div class="field-grid">${organizationField(r.contractor||'')}${field('Срок устранения','due',r.due||'','date')}<label class="field form-project-picker"><span>Рабочая документация</span><input id="workingDocSearch" name="workingDoc" type="text" value="${esc(r.workingDoc||'')}" placeholder="Шифр, слово или лист / узел" autocomplete="off" role="combobox" aria-autocomplete="list" aria-controls="workingDocSuggestions" aria-expanded="false"><div id="workingDocSuggestions" class="form-smart-suggestions hidden" role="listbox" aria-label="Разделы рабочей документации"></div></label>${field('Нормативное основание','standard',r.standard||'','text','Документ и пункт — если подтверждены')}<label class="field"><span>Статус</span><select name="status"><option ${r.status!=='Устранено'?'selected':''}>Открыто</option><option ${r.status==='Устранено'?'selected':''}>Устранено</option></select></label></div>${area('Описание несоответствия','description',r.description||'','Кратко и конкретно опишите выявленное нарушение')}${area('Требуемое устранение','remedy',r.remedy||'','Что необходимо выполнить')}${photoFields(r,'before','Фото замечания')}${photoFields(r,'after','Фото после устранения')}<div class="export-actions"><button type="button" class="secondary-btn" id="exportRemarkPdf">Сохранить карточку замечания в PDF</button><span class="hint">В PDF войдут данные карточки и обе группы фотографий.</span></div>`}
function photoForm(r){return `${baseFields(r)}${area('Описание фотоотчёта','description',r.description||'','Объект, участок и выполненные работы')}${photoFields(r,'photos','Фотографии')}`}
function numberRules(name=''){
 const value=String(name).toLocaleLowerCase('ru');
 const required=/акт|ведомост|аоср|атг/i.test(value);
 const numberable=required||/реестр|журнал|протокол|техническое решение/i.test(value);
 return{required,enabled:numberable};
}
function makeSection(name){const p=numberRules(name);return{id:uid(),name,numberEnabled:p.enabled,numberRequired:p.required,number:'',date:'',enabled:true,remarks:[]}}
function ensureSections(r){
 if(Array.isArray(r.sections))return r.sections;
 if(Array.isArray(r.docs)&&r.docs.length)r.sections=r.docs.map(d=>{const p=numberRules(d.name||'');return{id:d.id||uid(),name:d.name||'Раздел проверки',numberEnabled:p.enabled||!!d.number,numberRequired:p.required,number:d.number||'',date:d.date||'',enabled:true,remarks:d.note?.trim()?[{id:uid(),text:d.note.trim(),enabled:true}]:[],legacyFile:d.file?.name||''}});
 else r.sections=idTemplates.map(makeSection);
 return r.sections;
}
function sectionHeading(s){return `${s.name||'Раздел проверки'}${s.numberEnabled&&s.number?.trim()?` №${s.number.trim()}`:''}${s.date?` от ${dateRu(s.date)}`:''}`}
function dateRu(value){if(!value)return'';const m=String(value).match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?`${m[3]}.${m[2]}.${m[1]}`:String(value)}
function includedSections(r){return ensureSections(r).filter(s=>s.enabled!==false)}
function includedRemarks(r){let n=0;return includedSections(r).map(s=>({section:s,remarks:(s.remarks||[]).filter(x=>x.enabled!==false&&String(x.text||'').trim()).map(x=>({remark:x,number:++n}))}))}
function validateIdNumbers(r){const s=includedSections(r).find(x=>x.numberRequired&&(!x.numberEnabled||!x.number?.trim()));if(s){toast(`Укажите обязательный номер документа: ${s.name}`);return false}return true}
function idForm(r){const sections=ensureSections(r),n=sections.reduce((x,s)=>x+(s.enabled===false?0:(s.remarks||[]).filter(m=>m.enabled!==false&&m.text?.trim()).length),0);return `${baseFields(r,false)}${field('Название проверки','reportTitle',r.reportTitle||'Проверка исполнительной документации','text','Например: 4609 СК 303-ОВ, том 2',true)}<section class="registry-card id-docs-head"><div><strong>Документы к проверке</strong><p class="hint registry-summary">Откройте документ и внесите замечания вручную · ${sections.length} документов · ${n} замечаний</p></div><div class="add-section-row"><input id="newIdDocumentName" placeholder="Добавить документ в список"><button type="button" class="secondary-btn" id="addIdDocument">＋ Добавить</button></div></section><div class="registry-list id-document-list">${sections.map((s,i)=>`<article class="registry-item"><button type="button" class="registry-open" data-open-section="${i}"><span class="registry-number">${i+1}</span><span class="registry-doc-copy"><strong>${esc(sectionHeading(s))}</strong><small>${(s.remarks||[]).filter(m=>m.enabled!==false&&m.text?.trim()).length} замечаний${s.enabled===false?' · исключён из проверки':''}</small></span><span class="id-doc-chevron">›</span></button><div class="registry-actions"><button type="button" data-move-id-document="${i}" data-dir="-1" ${i===0?'disabled':''} aria-label="Переместить выше">↑</button><button type="button" data-move-id-document="${i}" data-dir="1" ${i===sections.length-1?'disabled':''} aria-label="Переместить ниже">↓</button><button type="button" class="registry-remove" data-delete-id-document="${i}" aria-label="Удалить документ">Удалить</button></div></article>`).join('')}</div>${area('Заключительный текст','conclusion',r.conclusion||'','Итог проверки и дальнейшие действия') }<div class="field-grid">${field('Должность','signerRole',r.signerRole||'','text','Должность проверяющего')}${field('ФИО','signerName',r.signerName||'','text','Фамилия, имя, отчество')}${field('Дата документа','signDate',r.signDate||today(),'date')}</div><div class="export-actions"><button type="button" class="secondary-btn" id="exportIdWord">Скачать Word (.docx)</button><button type="button" class="secondary-btn" id="exportIdPdf">Сохранить в PDF</button></div>`}
let sectionIndex=-1,remarkEditIndex=-1;
function renderSection(i,showRemark=false,editIndex=-1){
 sectionIndex=i;remarkEditIndex=editIndex;const s=ensureSections(draft)[i];if(!s)return;const rules=numberRules(s.name),remarks=s.remarks||(s.remarks=[]);
 $('#workflowContent').innerHTML=`<div class="dialog-head"><div><p class="eyebrow">ДОКУМЕНТ ${i+1} ИЗ ${draft.sections.length}</p><h2>${esc(s.name||'Документ проверки')}</h2><p class="muted">Запишите замечания по выбранному документу. После сохранения вернётесь к списку.</p></div><button type="button" class="icon-btn" id="closeIdDocument" aria-label="К списку документов">×</button></div><div class="workflow-body"><label class="field full"><span>Название документа</span><input id="sectionName" value="${esc(s.name||'')}"></label><div class="field-grid"><div class="field"><span>Номер документа</span><label class="switch"><input id="sectionNumberEnabled" type="checkbox" ${s.numberEnabled||rules.required?'checked':''} ${s.numberRequired||rules.required?'disabled':''}><span></span><b>Указывать номер</b></label></div><label class="field"><span>Дата документа</span><input id="sectionDate" type="date" value="${esc(s.date||'')}"></label></div><label class="field full ${s.numberEnabled||rules.required?'':'hidden'}" id="sectionNumberWrap"><span>№ документа ${s.numberRequired||rules.required?'· обязательно':''}</span><input id="sectionNumber" value="${esc(s.number||'')}" placeholder="Например: АОСР-303-17" ${s.numberRequired||rules.required?'required':''}></label><label class="switch section-enabled"><input id="sectionEnabled" type="checkbox" ${s.enabled===false?'':'checked'}><span></span><b>Включить документ в итоговую проверку</b></label><div class="remarks-head"><h3>Замечания · ${remarks.length}</h3><button type="button" class="secondary-btn" id="newRemark">＋ Добавить замечание</button></div><div class="remark-list">${remarks.map((m,j)=>`<article class="manual-remark"><div class="manual-remark-copy"><strong>${j+1}.</strong><p>${esc(m.text)}</p></div><label class="switch" title="Включить замечание в итоговый документ"><input type="checkbox" data-remark-toggle="${j}" ${m.enabled===false?'':'checked'}><span></span></label><div class="registry-actions"><button type="button" data-edit-remark="${j}">Изменить</button><button type="button" class="registry-remove" data-delete-remark="${j}">Удалить</button></div></article>`).join('')||'<p class="hint">Замечаний пока нет. Нажмите «Добавить замечание», чтобы внести текст вручную.</p>'}</div>${showRemark?`<div class="remark-editor"><label class="field full"><span>Текст замечания</span><textarea id="manualRemarkText" placeholder="Введите замечание по этому документу">${esc(editIndex>=0?remarks[editIndex]?.text||'':'')}</textarea></label><div><button type="button" class="secondary-btn" id="cancelRemark">Отмена</button><button type="button" class="primary-btn" id="saveRemark">Сохранить</button></div></div>`:''}</div><div class="dialog-actions"><button type="button" class="secondary-btn" id="sectionCancel">К списку документов</button><span class="spacer"></span><button type="button" class="primary-btn" id="sectionDone">Сохранить и вернуться к списку</button></div>`;
 const root=$('#workflowContent'),returnToList=()=>{$('#workflowDialog').close();paintEditor(draft)};
 $('#closeIdDocument').onclick=returnToList;$('#sectionCancel').onclick=returnToList;
 $('#sectionDone').onclick=async()=>{if(!saveSectionFields())return;const saved=await persistCard(false);if(saved){$('#workflowDialog').close();paintEditor(draft);toast('Изменения сохранены')}};
 $('#sectionNumberEnabled').onchange=()=>{const old=s.number;saveSectionFields();s.numberEnabled=$('#sectionNumberEnabled').checked||s.numberRequired;s.number=old;paintEditor(draft);renderSection(i,showRemark,editIndex)};
 $('#sectionEnabled').onchange=()=>{if(!saveSectionFields())return;s.enabled=$('#sectionEnabled').checked;paintEditor(draft);renderSection(i,showRemark,editIndex)};
 $('#newRemark').onclick=()=>{if(saveSectionFields()){paintEditor(draft);renderSection(i,true,-1)}};
 $('#cancelRemark')?.addEventListener('click',()=>renderSection(i));
 $('#saveRemark')?.addEventListener('click',async()=>{const text=$('#manualRemarkText').value.trim();if(!text){toast('Введите текст замечания');$('#manualRemarkText').focus();return}if(!saveSectionFields())return;if(editIndex>=0)remarks[editIndex].text=text;else remarks.push({id:uid(),text,enabled:true});const saved=await persistCard(false);if(saved){$('#workflowDialog').close();paintEditor(draft);toast('Замечание сохранено')}});
 root.querySelectorAll('[data-remark-toggle]').forEach(b=>b.onchange=()=>{if(!saveSectionFields())return;remarks[+b.dataset.remarkToggle].enabled=b.checked;paintEditor(draft);renderSection(i)});
 root.querySelectorAll('[data-edit-remark]').forEach(b=>b.onclick=()=>{if(saveSectionFields()){paintEditor(draft);renderSection(i,true,+b.dataset.editRemark)}});
 root.querySelectorAll('[data-delete-remark]').forEach(b=>b.onclick=()=>{if(!saveSectionFields())return;const j=+b.dataset.deleteRemark;if(confirm('Удалить замечание?')){remarks.splice(j,1);paintEditor(draft);renderSection(i)}})
}
function saveSectionFields(){const s=draft.sections[sectionIndex],name=$('#sectionName').value.trim(),rules=numberRules(name);if(!name){toast('Укажите название раздела');return false}s.name=name;s.numberRequired=rules.required;s.numberEnabled=s.numberRequired||$('#sectionNumberEnabled').checked;s.number=s.numberEnabled?$('#sectionNumber').value.trim():'';s.date=$('#sectionDate').value;s.enabled=$('#sectionEnabled').checked;return true}

async function persistCard(validateNumbers=true){captureDraft(draft);const form=$('#recordForm'),project=pick(form,'project');if(!project){toast('Укажите объект в карточке');form.elements.project.focus();return null}const r={...draft,id:editing||draft.id||uid(),type:'id',project,date:pick(form,'date')||today(),place:pick(form,'place'),reportTitle:pick(form,'reportTitle')||'Проверка исполнительной документации',conclusion:pick(form,'conclusion'),signerRole:pick(form,'signerRole'),signerName:pick(form,'signerName'),signDate:pick(form,'signDate'),updated:new Date().toISOString()};if(validateNumbers&&!validateIdNumbers(r))return null;await put(r);records=await all();draft=r;return r}
async function persistRemarkCard(){captureDraft(draft);const form=$('#recordForm'),project=pick(form,'project');if(!project){toast('Укажите объект');form.elements.project.focus();return null}const r={...draft,id:editing||draft.id||uid(),type:'remarks',project,numberEnabled:form.elements.namedItem('numberEnabled')?.checked||false,number:pick(form,'number'),date:pick(form,'date')||today(),place:pick(form,'place'),contractor:pick(form,'contractor'),due:pick(form,'due'),status:pick(form,'status')||'Открыто',workingDoc:pick(form,'workingDoc'),standard:pick(form,'standard'),description:pick(form,'description'),remedy:pick(form,'remedy'),perPage:pick(form,'perPage')||'2',before:draft.before||[],after:draft.after||[],updated:new Date().toISOString()};await put(r);records=await all();draft=r;return r}
async function persistPhotoCard(){captureDraft(draft);const form=$('#recordForm'),project=pick(form,'project');if(!project){toast('Укажите объект');form.elements.project.focus();return null}const r={...draft,id:editing||draft.id||uid(),type:'photos',project,date:pick(form,'date')||today(),place:pick(form,'place'),description:pick(form,'description'),perPage:pick(form,'perPage')||'2',photos:draft.photos||[],updated:new Date().toISOString()};await put(r);records=await all();draft=r;return r}
async function generateRemarkPdf(r){try{toast('Формирую PDF…');await ensurePdf();const photos=list=>(list||[]).map(item=>typeof item==='string'?{src:item}:item).filter(item=>item?.src);const number=remarkNumberIsEnabled(r)?String(r.number||'').trim():'';const record={number,numberEnabled:remarkNumberIsEnabled(r),issuer:'',date:r.date,status:r.status||'Открыто',object:r.project,location:r.place,contractor:r.contractor,description:r.description,workingDoc:r.workingDoc,ntd:r.standard?[{name:r.standard}]:[],remedy:r.remedy,dueDate:r.due,photosBefore:photos(r.before),photosAfter:photos(r.after),perPage:r.perPage||2};const bytes=await RksPdf.build(record,false);downloadBlob(new Blob([bytes],{type:'application/pdf'}),`РКС_Замечание_${safeFilename(r.project)}_${r.date||today()}.pdf`);toast('PDF карточки замечания сформирован')}catch(error){console.error(error);toast(`Не удалось сформировать PDF: ${error.message||'ошибка'}`)}}
async function generatePhotoReportPdf(r){try{toast('Формирую PDF фотоотчёта…');await ensurePdf();const record={number:r.number||`ФОТО-${String(r.date||today()).replaceAll('-','')}-${String(r.id||'').slice(0,6).toUpperCase()}`,project:r.project||'',place:r.place||'',date:r.date||'',description:r.description||'',photos:(r.photos||[]).map(src=>typeof src==='string'?{src}:src),perPage:r.perPage||2};const bytes=await RksPdf.buildPhotoReport(record);downloadBlob(new Blob([bytes],{type:'application/pdf'}),`РКС_Фотоотчёт_${safeFilename(r.project)}_${r.date||today()}.pdf`);toast('PDF фотоотчёта сформирован')}catch(error){console.error(error);toast(`Не удалось сформировать PDF: ${error.message||'ошибка'}`)}}
function dataBytes(uri){const b=atob(uri.split(',')[1]);return Uint8Array.from(b,c=>c.charCodeAt(0))}
async function loadLogo(){const res=await fetch(new URL('logo.png',location.href));if(!res.ok)throw Error('Не удалось загрузить логотип');return new Uint8Array(await res.arrayBuffer())}
function safeFilename(s){return String(s||'объект').replace(/[<>:"/\\|?*]+/g,'_').trim().slice(0,60)||'объект'}
const scriptLoads=new Map();
function loadScript(src){if(!scriptLoads.has(src))scriptLoads.set(src,new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=src;script.onload=resolve;script.onerror=()=>{scriptLoads.delete(src);reject(Error('Не удалось загрузить '+src))};document.head.appendChild(script)}));return scriptLoads.get(src)}
let pdfReady;
function ensurePdf(){if(!pdfReady)pdfReady=(async()=>{await loadScript('vendor/pdf-lib.min.js');await loadScript('vendor/fontkit.umd.min.js');await loadScript('pdf.js')})().catch(e=>{pdfReady=null;throw e});return pdfReady}
function ensureWord(){return loadScript('docx.bundle.js')}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
async function downloadIdWord(r){try{await ensureWord();const D=window.DocxLib;if(!D)throw Error('Не удалось загрузить модуль Word');const {Document,Packer,Paragraph,TextRun,ImageRun,AlignmentType}=D,children=[],font='Arial',size=24;const logo=await loadLogo();children.push(new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:240},children:[new ImageRun({data:logo,transformation:{width:220,height:55}})]}));const para=(text,{bold=false,center=false,after=140}={})=>{const runs=String(text||'').split(/\r?\n/).flatMap((line,i)=>[...(i?[new TextRun({break:1})]:[]),new TextRun({text:line,font,size,bold})]);children.push(new Paragraph({alignment:center?AlignmentType.CENTER:AlignmentType.LEFT,spacing:{after},children:runs}))};para(r.reportTitle||'Документ проверки исполнительной документации',{bold:true,center:true,after:260});if(r.project)para(`Объект: ${r.project}`);if(r.place)para(`Место / участок: ${r.place}`);if(r.date)para(`Дата проверки: ${dateRu(r.date)}`,{after:220});for(const {section,remarks} of includedRemarks(r)){para(sectionHeading(section),{bold:true,after:90});for(const {remark,number} of remarks)para(`${number}. ${remark.text}`,{after:130})}para('Заключение',{bold:true,after:80});para(r.conclusion||'____________________________',{after:260});para(`Должность: ${r.signerRole||'____________________________'}`);para(`ФИО: ${r.signerName||'____________________________'}`);para(`Дата: ${r.signDate?dateRu(r.signDate):'__.__.____'}`,{after:200});const doc=new Document({sections:[{properties:{},children}]});const blob=await Packer.toBlob(doc);downloadBlob(blob,`РКС_Документ_проверки_ИД_${safeFilename(r.project)}_${r.date||today()}.docx`);toast('Файл Word сформирован')}catch(err){console.error(err);toast('Не удалось сформировать Word: '+(err.message||'ошибка'))}}
document.addEventListener('click',async e=>{if(e.target.closest('#exportIdWord')){const r=await persistCard();if(r)await downloadIdWord(r);return}if(e.target.closest('#exportIdPdf')){const win=window.open('','_blank'),r=await persistCard();if(r)printRecord(r.id,win);else win?.close();return}if(e.target.closest('#exportRemarkPdf')){const r=await persistRemarkCard();if(r)await generateRemarkPdf(r);return}if(e.target.closest('#exportCardPdf')){const r=await persistPhotoCard();if(r)await generatePhotoReportPdf(r)}});

async function compress(file){if(file.size>15*1024*1024)throw Error('Фото больше 15 МБ');return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const scale=Math.min(1,1600/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);resolve(c.toDataURL('image/jpeg',.8))};img.onerror=()=>{URL.revokeObjectURL(url);reject(Error('Не удалось прочитать фото'))};img.src=url})}
function fileData(file){if(file.size>4*1024*1024)throw Error(`Файл «${file.name}» больше 4 МБ`);return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve({name:file.name,type:file.type,data:r.result});r.onerror=()=>reject(r.error);r.readAsDataURL(file)})}
function captureDraft(rec){const form=$('#recordForm');if(form.dataset.type!==rec.type)return;const f=n=>pick(form,n);rec.project=f('project');rec.date=f('date')||today();rec.place=f('place');if(rec.type==='remarks')Object.assign(rec,{numberEnabled:form.elements.namedItem('numberEnabled')?.checked||false,number:f('number'),contractor:f('contractor'),due:f('due'),status:f('status'),workingDoc:f('workingDoc'),standard:f('standard'),description:f('description'),remedy:f('remedy'),perPage:f('perPage')||'2'});if(rec.type==='photos')Object.assign(rec,{description:f('description'),perPage:f('perPage')||'2'});if(rec.type==='id')Object.assign(rec,{reportTitle:f('reportTitle'),conclusion:f('conclusion'),signerRole:f('signerRole'),signerName:f('signerName'),signDate:f('signDate')})}
function paintEditor(rec){draft=rec;$('#formTitle').textContent=editing?`Изменить · ${modules[rec.type].label}`:modules[rec.type].add;$('#formEyebrow').textContent=editing?'РЕДАКТИРОВАНИЕ':'НОВАЯ ЗАПИСЬ';$('#deleteBtn').classList.toggle('hidden',!editing);$('#exportCardPdf').classList.toggle('hidden',rec.type!=='photos');const fields=$('#formFields');fields.innerHTML=rec.type==='remarks'?remarkForm(rec):rec.type==='photos'?photoForm(rec):idForm(rec);bindFormProjectSearch(fields);bindFormRDSearch(fields);if(rec.type==='remarks')bindRemarkNumber(fields);if(rec.type==='id')bindIdDocuments(fields);const form=$('#recordForm');form.dataset.type=rec.type;form.onsubmit=saveForm;fields.querySelectorAll('[data-photo-layout]').forEach(sel=>sel.onchange=()=>fields.querySelectorAll('[data-photo-layout]').forEach(other=>other.value=sel.value));fields.querySelectorAll('[data-photos]').forEach(inp=>inp.onchange=async ev=>{captureDraft(rec);const key=ev.currentTarget.dataset.photos;try{for(const f of ev.currentTarget.files){if((rec[key]||[]).length>=12)break;(rec[key]??=[]).push(await compress(f))}paintEditor(rec)}catch(e){toast(e.message)}});fields.querySelectorAll('[data-remove-photo]').forEach(b=>b.onclick=()=>{captureDraft(rec);rec[b.dataset.removePhoto].splice(+b.dataset.index,1);paintEditor(rec)});fields.querySelectorAll('[data-doc-file]').forEach(inp=>inp.onchange=async ev=>{captureDraft(rec);try{const f=ev.currentTarget.files[0];if(!f)return;rec.docs[+ev.currentTarget.dataset.docFile].file=await fileData(f);paintEditor(rec);toast('Файл добавлен в комплект')}catch(e){toast(e.message)}})}
function editor(r=null){editing=r?.id||null;const type=r?.type||module;const rec=r||{id:uid(),type,sections:type==='id'?idTemplates.map(makeSection):[]};if(!r&&type==='remarks'){rec.numberEnabled=true;rec.number=nextRemarkNumber()}if(type==='id')ensureSections(rec);paintEditor(rec);$('#editor').showModal()}
function pick(form,name){return form.elements.namedItem(name)?.value?.trim()||''}
async function saveForm(ev){ev.preventDefault();const form=ev.currentTarget,type=form.dataset.type,existing=records.find(r=>r.id===(editing||draft.id));captureDraft(draft);let r={...(existing||{}),...draft,id:editing||draft.id||uid(),type,project:pick(form,'project'),date:pick(form,'date')||today(),place:pick(form,'place'),updated:new Date().toISOString()};if(!r.project){toast('Укажите объект');form.elements.project.focus();return}if(type==='remarks')Object.assign(r,{numberEnabled:form.elements.namedItem('numberEnabled')?.checked||false,number:pick(form,'number'),contractor:pick(form,'contractor'),due:pick(form,'due'),status:pick(form,'status')||'Открыто',workingDoc:pick(form,'workingDoc'),standard:pick(form,'standard'),description:pick(form,'description'),remedy:pick(form,'remedy'),perPage:pick(form,'perPage')||'2',before:draft.before||[],after:draft.after||[]});if(type==='photos')Object.assign(r,{description:pick(form,'description'),perPage:pick(form,'perPage')||'2',photos:draft.photos||[]});if(type==='id'){r.reportTitle=pick(form,'reportTitle')||'Документ проверки исполнительной документации';r.conclusion=pick(form,'conclusion');r.signerRole=pick(form,'signerRole');r.signerName=pick(form,'signerName');r.signDate=pick(form,'signDate');r.sections=ensureSections(draft)}await put(r);records=await all();$('#editor').close();toast('Запись сохранена');render()}
function edit(id){const r=records.find(x=>x.id===id);if(r)editor(structuredClone(r))}
function printRecord(id,providedWindow=null){
 const r=records.find(x=>x.id===id);if(!r){providedWindow?.close();return}
 const logoUrl=new URL('logo.png',location.href).href;
 let body='';
 if(r.type==='id'){
  const sections=includedRemarks(r).map(({section,remarks})=>`<section class="id-section"><h2>${esc(sectionHeading(section))}</h2>${remarks.map(({remark,number})=>`<p class="id-remark"><b>${number}.</b> ${esc(remark.text)}</p>`).join('')}</section>`).join('');
  body=`<h1>${esc(r.reportTitle||'Документ проверки исполнительной документации')}</h1><p class="doc-meta"><b>Объект:</b> ${esc(r.project||'—')}${r.place?`<br><b>Место / участок:</b> ${esc(r.place)}`:''}${r.date?`<br><b>Дата проверки:</b> ${dateRu(r.date)}`:''}</p>${sections}<section class="conclusion"><h2>Заключение</h2><p>${esc(r.conclusion||'____________________________')}</p></section><div class="sign-off"><p>Должность: ${esc(r.signerRole||'____________________________')}</p><p>ФИО: ${esc(r.signerName||'____________________________')}</p><p>Дата: ${r.signDate?dateRu(r.signDate):'__.__.____'}</p></div>`;
 }else{
  body=`<h1>${esc(r.type==='remarks'?'Карточка замечания':r.title||modules[r.type].label)}</h1><p class="doc-meta"><b>Объект:</b> ${esc(r.project||'—')}<br><b>Дата:</b> ${niceDate(r.date)}${r.place?`<br><b>Место / участок:</b> ${esc(r.place)}`:''}</p>${r.type==='remarks'&&r.contractor?`<p><b>Ответственная организация:</b> ${esc(r.contractor)}</p>`:''}${r.type==='remarks'&&r.due?`<p><b>Срок устранения:</b> ${niceDate(r.due)}</p>`:''}${r.type==='remarks'?`<p><b>Статус:</b> ${esc(r.status||'Открыто')}</p>`:''}${r.description?`<section><h2>Описание несоответствия</h2><p class="preline">${esc(r.description)}</p></section>`:''}${r.workingDoc?`<p><b>Рабочая документация:</b> ${esc(r.workingDoc)}</p>`:''}${r.standard?`<p><b>Нормативное основание:</b> ${esc(r.standard)}</p>`:''}${r.remedy?`<section><h2>Требуемое устранение</h2><p class="preline">${esc(r.remedy)}</p></section>`:''}`;
 }
 const pics=r.type==='photos'?(r.photos||[]):r.type==='remarks'?[...(r.before||[]),...(r.after||[])]:r.type==='id'?(r.docs||[]).filter(d=>d.file?.type?.startsWith('image/')).map(d=>d.file.data):[];
 const perPage=['1','2','4','6'].includes(String(r.perPage))?Number(r.perPage):2,photoChunks=[];for(let i=0;i<pics.length;i+=perPage)photoChunks.push(pics.slice(i,i+perPage));
 const makePhotoPages=(items,label)=>{const chunks=[];for(let i=0;i<items.length;i+=perPage)chunks.push(items.slice(i,i+perPage));return chunks.map((chunk,i)=>`<section class="photo-page per-${perPage}"><h2>${esc(label)}${chunks.length>1?` · лист ${i+1}`:''}</h2><div class="photo-grid">${chunk.map(src=>`<img src="${src}" alt="Фотофиксация">`).join('')}</div></section>`).join('')};
 const photoBlock=r.type==='remarks'?`${r.before?.length?`<div class="photo-pages">${makePhotoPages(r.before,'Фото замечания')}</div>`:''}${r.after?.length?`<div class="photo-pages">${makePhotoPages(r.after,'Фото после устранения')}</div>`:''}`:pics.length?`<div class="photo-pages">${makePhotoPages(pics,'Фотоматериалы')}</div>`:'';
 const w=providedWindow||window.open('','_blank');if(!w){toast('Разрешите всплывающее окно для печати');return}
 w.document.write(`<!doctype html><html lang="ru"><meta charset="utf-8"><title>${esc(r.type==='remarks'?'Карточка замечания':r.reportTitle||r.title||modules[r.type].label)}</title><style>body{font:12pt Arial,sans-serif;color:#172433;max-width:900px;margin:32px auto;line-height:1.45}.print-brand img{display:block;width:220px;height:auto;margin:0 0 20px}h1{font-size:12pt;text-align:center;margin:0 0 16pt}h2{font-size:12pt;margin:14pt 0 7pt;page-break-after:avoid}.doc-meta{margin-bottom:14pt}.preline{white-space:pre-wrap}.id-section{margin:0 0 9pt}.id-remark{margin:0 0 8pt;text-align:justify;white-space:pre-wrap}.sign-off{margin-top:26pt}.sign-off p{margin:5pt 0}.muted{color:#627386}@page{size:A4;margin:20mm}.photo-pages{break-before:page}.photo-page{height:9.8in;display:flex;flex-direction:column;break-after:page;page-break-after:always}.photo-page:last-child{break-after:auto;page-break-after:auto}.photo-grid{flex:1;min-height:0;display:grid;gap:8px;grid-template-columns:1fr;grid-template-rows:repeat(2,minmax(0,1fr))}.per-1 .photo-grid{grid-template-columns:1fr;grid-template-rows:1fr}.per-2 .photo-grid{grid-template-columns:1fr;grid-template-rows:repeat(2,minmax(0,1fr))}.per-4 .photo-grid{grid-template-columns:repeat(2,minmax(0,1fr));grid-template-rows:repeat(2,minmax(0,1fr))}.per-6 .photo-grid{grid-template-columns:repeat(2,minmax(0,1fr));grid-template-rows:repeat(3,minmax(0,1fr))}.photo-grid img{width:100%;height:100%;min-height:0;object-fit:contain;break-inside:avoid}@media print{body{margin:0;max-width:none}}</style><header class="print-brand"><img src="${logoUrl}" alt="ФАУ «РосКапСтрой»"></header>${body}${photoBlock}<script>onload=()=>print()<\/script></html>`);w.document.close();
}

function exportBackup(){const blob=new Blob([JSON.stringify({kind:'RKS-Control-Backup',version:1,exportedAt:new Date().toISOString(),records},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`РКС_Контроль_резервная_копия_${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Резервная копия выгружена')}
async function restore(file){try{const d=JSON.parse(await file.text());if(d.kind!=='RKS-Control-Backup'||!Array.isArray(d.records))throw Error('Формат резервной копии не распознан');for(const r of d.records)if(['remarks','photos','id'].includes(r.type)&&r.id)await put(r);records=await all();render();toast('Данные восстановлены')}catch(e){toast(e.message||'Не удалось прочитать копию')}}
$('#addBtn').onclick=()=>editor();$('#closeEditor').onclick=()=>$('#editor').close();$('#cancelBtn').onclick=()=>$('#editor').close();$('#deleteBtn').onclick=async()=>{if(editing&&confirm('Удалить эту запись без возможности восстановления?')){await del(editing);records=await all();$('#editor').close();render();toast('Запись удалена')}};$('#restoreInput').onchange=()=>$('#restoreInput').files[0]&&restore($('#restoreInput').files[0]);bindSmartSearch();bindMobileChrome();
(async()=>{try{db=await openDB();records=await all();render()}catch(e){$('#recordList').innerHTML='<div class="empty"><h3>Не удалось открыть локальное хранилище</h3><p>Откройте приложение в современном браузере и разрешите хранение данных.</p></div>';console.error(e)}})();
})();
