import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, Download, FileText, MoreHorizontal, Plus, Trash2 } from 'lucide-react';
import { db, nextNumber } from '../db/database';
import { downloadBlob } from '../services/backup';
import { validateDefectForIssue } from '../services/validation';
import { createDefect, type Defect, type DefectStatus, type DocumentReference, type Inspection, type InspectionKind, type PhotoReport, type ScenarioStep, type WorkDrawingReference } from '../types/models';
import { PhotoIdsPicker, ReportPhotosPicker } from '../components/PhotoPicker';
import { Button, Field, IconButton, Input, Modal, Section, Select, Textarea } from '../components/ui';

type RecordType = Defect | Inspection | PhotoReport;
const disciplines = ['ЭМ — Силовое электрооборудование и электроосвещение', 'ЭС — Электроснабжение', 'ЭО — Электроосвещение', 'ЭГ — Заземление и молниезащита', 'СС — Слаботочные системы', 'АПС — Автоматическая пожарная сигнализация', 'СОУЭ — Система оповещения и управления эвакуацией', 'СКУД — Система контроля и управления доступом', 'СВН — Система видеонаблюдения', 'АТХ — Автоматизация технологических процессов', 'АК — Автоматизация и контроль', 'ПНР — Пусконаладочные работы', 'ИД — Исполнительная документация'];
const defectTypes = ['Несоответствие РД', 'Нарушение НТД', 'Некачественный монтаж', 'Отсутствие маркировки', 'Нарушение заземления', 'Кабельные линии', 'Нарушение пожарной безопасности', 'Нарушение требований взрывозащиты', 'Неполнота документации', 'Повреждение', 'Несогласованное отклонение', 'Другое'];
const statuses: DefectStatus[] = ['Черновик', 'Выдано', 'В работе', 'На проверке', 'Устранено', 'Закрыто', 'Архив'];
const knownObjects = [{ gp: '303', name: 'Пересыпная станция №3' }, { gp: '402', name: 'Станция размораживания вагонов' }, { gp: '207', name: 'Конвейерная эстакада №11' }, { gp: '206', name: 'Конвейерная эстакада' }, { gp: '702', name: 'Система электрохимической защиты' }];

export function RecordEditor({ initial, onClose, onSaved, onDelete }: { initial: RecordType; onClose: () => void; onSaved: () => void; onDelete: (record: RecordType) => void }) {
  const [record, setRecord] = useState<RecordType>(initial); const [saveState, setSaveState] = useState<'saving' | 'saved' | 'error'>('saved'); const [pdfBusy, setPdfBusy] = useState(false); const [progress, setProgress] = useState(0); const [menuOpen, setMenuOpen] = useState(false); const latest = useRef(record); const revision = useRef(initial.revision); const lastUniqueNumber = useRef(initial.number); latest.current = record;
  const table = useMemo(() => record.type === 'defect' ? db.defects : record.type === 'inspection' ? db.inspections : db.photoReports, [record.type]);
  const persist = useCallback(async (value: RecordType) => {
    setSaveState('saving');
    try {
      const next = { ...value, updatedAt: new Date().toISOString(), revision: ++revision.current } as RecordType;
      if (next.type === 'defect') await db.defects.put(next); else if (next.type === 'inspection') await db.inspections.put(next); else await db.photoReports.put(next);
      if (next.type !== 'photoReport') {
        const now = new Date().toISOString();
        const refs = [next.object.gp || next.object.name ? { id: `object:${next.object.gp}:${next.object.name}`, type: 'object' as const, value: next.object.name, gp: next.object.gp, createdAt: now } : undefined, next.contractor ? { id: `contractor:${next.contractor.toLocaleLowerCase('ru')}`, type: 'contractor' as const, value: next.contractor, createdAt: now } : undefined, next.discipline ? { id: `discipline:${next.discipline}`, type: 'discipline' as const, value: next.discipline, createdAt: now } : undefined, next.workType ? { id: `workType:${next.workType.toLocaleLowerCase('ru')}`, type: 'workType' as const, value: next.workType, createdAt: now } : undefined].filter(item => item !== undefined);
        await db.dictionaries.bulkPut(refs);
      }
      if (latest.current.id === next.id) latest.current = next;
      setSaveState('saved'); onSaved();
    } catch (error) { console.error(error); setSaveState('error'); }
  }, [onSaved]);
  useEffect(() => { const timeout = setTimeout(() => void persist(record), 550); return () => clearTimeout(timeout); }, [record, persist]);
  useEffect(() => { const flush = () => void persist(latest.current); document.addEventListener('visibilitychange', flush); window.addEventListener('pagehide', flush); return () => { document.removeEventListener('visibilitychange', flush); window.removeEventListener('pagehide', flush); }; }, [persist]);

  async function makePdf() {
    if (record.type === 'defect' && record.status !== 'Черновик') {
      const issues = validateDefectForIssue(record); if (issues.length) { alert(`Для официального PDF заполните:\n• ${issues.map(x => x.label).join('\n• ')}`); document.querySelector<HTMLElement>(`[data-field="${issues[0].field}"]`)?.scrollIntoView({ behavior: 'smooth', block: 'center' }); return; }
      if (record.ntd.some(item => !item.title.trim() || !item.clauses.trim())) { alert('Заполните название и пункты во всех записях НТД.'); return; }
    }
    setPdfBusy(true); setProgress(4);
    try {
      await persist(record);
      const { generateDefectPdf, generateInspectionPdf, generatePhotoReportPdf } = await import('../pdf/generatePdf');
      const result = record.type === 'defect' ? await generateDefectPdf(record) : record.type === 'inspection' ? await generateInspectionPdf(record) : await generatePhotoReportPdf(record, setProgress);
      setProgress(100);
      if (navigator.share && navigator.canShare?.({ files: [new File([result.blob], result.filename, { type: 'application/pdf' })] })) await navigator.share({ files: [new File([result.blob], result.filename, { type: 'application/pdf' })], title: result.filename }); else downloadBlob(result.blob, result.filename);
    } catch (error) { alert(`PDF не сформирован. ${error instanceof Error ? error.message : 'Недостаточно памяти или повреждено вложение.'}`); } finally { setPdfBusy(false); setProgress(0); }
  }

  async function duplicate() {
    const module = record.type === 'defect' ? 'defects' : record.type === 'inspection' ? 'inspections' : 'photoReports';
    const copy = { ...record, id: crypto.randomUUID(), number: await nextNumber(module), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), revision: 1 } as RecordType;
    if (copy.type === 'defect') { copy.status = 'Черновик'; await db.defects.add(copy); } else if (copy.type === 'inspection') await db.inspections.add(copy); else await db.photoReports.add(copy);
    setMenuOpen(false); onSaved(); alert(`Создана копия ${copy.number}. Она доступна в журнале.`);
  }

  function exportRecord() { const blob = new Blob([JSON.stringify(record, null, 2)], { type: 'application/json' }); downloadBlob(blob, `${record.number}.json`); setMenuOpen(false); }
  async function checkNumber() {
    const duplicates = record.type === 'defect' ? await db.defects.where('number').equals(record.number).toArray() : record.type === 'inspection' ? await db.inspections.where('number').equals(record.number).toArray() : await db.photoReports.where('number').equals(record.number).toArray();
    if (!duplicates.some(item => item.id !== record.id)) { lastUniqueNumber.current = record.number; return; }
    const choice = prompt('Такой номер уже существует. Введите 1 — сохранить номер, 2 — назначить следующий свободный номер, 3 — отменить изменение.', '2');
    if (choice === '1') return;
    if (choice === '2') { const module = record.type === 'defect' ? 'defects' : record.type === 'inspection' ? 'inspections' : 'photoReports'; const number = await nextNumber(module); lastUniqueNumber.current = number; setRecord({ ...record, number } as RecordType); return; }
    setRecord({ ...record, number: lastUniqueNumber.current } as RecordType);
  }

  return <div className="editor-view"><header className="editor-toolbar"><IconButton label="Назад в журнал" onClick={onClose}><ArrowLeft /></IconButton><strong>{record.number}</strong><Button variant="ghost" loading={pdfBusy} onClick={() => void makePdf()}><FileText />PDF</Button><IconButton label="Действия" onClick={() => setMenuOpen(true)}><MoreHorizontal /></IconButton></header>
    {pdfBusy && <div className="progress" aria-label={`Формирование PDF: ${progress}%`}><span style={{ width: `${Math.max(progress, 12)}%` }} /></div>}
    <main className="editor-content" onBlurCapture={event => { if ((event.target as HTMLElement).dataset.field === 'number') void checkNumber(); }}>
      <p className={`save-state save-state--${saveState}`}>{saveState === 'saving' ? 'Сохранение…' : saveState === 'saved' ? 'Сохранено' : 'Не удалось сохранить. Проверьте свободное место.'}</p>
      {record.type === 'defect' ? <DefectForm value={record} onChange={setRecord} onNumberBlur={() => void checkNumber()} /> : record.type === 'inspection' ? <InspectionForm value={record} onChange={setRecord} onNumberBlur={() => void checkNumber()} /> : <PhotoReportForm value={record} onChange={setRecord} onNumberBlur={() => void checkNumber()} onPdf={() => void makePdf()} pdfBusy={pdfBusy} />}
      <Button className="delete-record" variant="danger" onClick={() => { if (confirm(`Удалить ${record.number}? Действие можно отменить из уведомления журнала.`)) onDelete(record); }}><Trash2 />Удалить запись</Button>
    </main><Modal open={menuOpen} title={`Действия — ${record.number}`} onClose={() => setMenuOpen(false)}><div className="filter-options">{record.type === 'defect' && <button onClick={() => { setRecord({ ...record, status: 'Архив' }); setMenuOpen(false); }}>Переместить в архив</button>}<button onClick={() => void duplicate()}>Дублировать</button><button onClick={exportRecord}>Экспортировать запись JSON</button><Button variant="danger" onClick={() => { if (confirm(`Удалить ${record.number}?`)) onDelete(record); }}>Удалить запись</Button></div></Modal>
  </div>;
}

function DefectForm({ value, onChange, onNumberBlur }: { value: Defect; onChange: (value: Defect) => void; onNumberBlur: () => void }) {
  const set = <K extends keyof Defect>(key: K, next: Defect[K]) => onChange({ ...value, [key]: next });
  function addNtd() { set('ntd', [...value.ntd, { id: crypto.randomUUID(), title: '', clauses: '' }]); }
  function patchNtd(id: string, patch: Partial<DocumentReference>) { set('ntd', value.ntd.map(item => item.id === id ? { ...item, ...patch } : item)); }
  function addDrawing() { set('drawings', [...value.drawings, { id: crypto.randomUUID(), code: '' }]); }
  function patchDrawing(id: string, patch: Partial<WorkDrawingReference>) { set('drawings', value.drawings.map(item => item.id === id ? { ...item, ...patch } : item)); }
  return <>
    <Section title="Общие сведения"><div className="form-grid"><Field label="Номер"><Input data-field="number" value={value.number} onChange={e => set('number', e.target.value)} /></Field><Field label="Дата выявления"><Input data-field="date" type="date" value={value.date} onChange={e => set('date', e.target.value)} /></Field><Field label="Статус"><Select value={value.status} onChange={e => { const status = e.target.value as DefectStatus; if (value.status === 'Закрыто' && status !== 'Закрыто' && !confirm('Вернуть закрытое замечание в работу?')) return; set('status', status); }}>{statuses.map(item => <option key={item}>{item}</option>)}</Select></Field><Field label="Критичность"><Select value={value.severity} onChange={e => set('severity', e.target.value as Defect['severity'])}><option>Обычное</option><option>Существенное</option><option>Критическое</option></Select></Field><Field label="Плановая дата устранения"><Input data-field="plannedDate" type="date" value={value.plannedDate} onChange={e => set('plannedDate', e.target.value)} /></Field><Field label="Фактическая дата устранения"><Input type="date" value={value.resolvedDate ?? ''} onChange={e => set('resolvedDate', e.target.value)} /></Field></div><Field label="Кем выдано"><Input data-field="issuer" value={value.issuer} onChange={e => set('issuer', e.target.value)} /></Field></Section>
    <Section title="Объект"><div data-field="object" className="object-pair"><Field label="№ ГП"><Input list="gp-list" value={value.object.gp} placeholder="303" onChange={e => { const match = knownObjects.find(x => x.gp === e.target.value); set('object', { gp: e.target.value, name: match?.name ?? value.object.name }); }} /><datalist id="gp-list">{knownObjects.map(item => <option key={item.gp} value={item.gp}>{item.name}</option>)}</datalist></Field><Field label="Название объекта"><Input value={value.object.name} placeholder="Пересыпная станция №3" onChange={e => set('object', { ...value.object, name: e.target.value })} /></Field></div><Field label="Место / отметка / оборудование"><Input data-field="location" value={value.location} onChange={e => set('location', e.target.value)} /></Field></Section>
    <Section title="Классификация"><div className="form-grid"><Field label="Раздел работ"><Select data-field="discipline" value={value.discipline} onChange={e => set('discipline', e.target.value)}><option value="">Выберите раздел</option>{disciplines.map(item => <option key={item}>{item}</option>)}</Select></Field><Field label="Вид работ"><Input value={value.workType} placeholder="Монтаж кабельных линий" onChange={e => set('workType', e.target.value)} /></Field><Field label="Тип недостатка"><Select value={value.defectType} onChange={e => set('defectType', e.target.value)}><option value="">Выберите тип</option>{defectTypes.map(item => <option key={item}>{item}</option>)}</Select></Field><Field label="Подрядчик"><Input data-field="contractor" value={value.contractor} onChange={e => set('contractor', e.target.value)} /></Field></div></Section>
    <Section title="Содержание замечания"><Field label="Описание недостатка"><Textarea data-field="description" value={value.description} onChange={e => set('description', e.target.value)} /></Field><Field label="Указания по устранению"><Textarea value={value.resolution} onChange={e => set('resolution', e.target.value)} /></Field><div className="form-grid"><Field label="Ответственный"><Input value={value.responsible} onChange={e => set('responsible', e.target.value)} /></Field><Field label="Служебное примечание"><Input value={value.note} onChange={e => set('note', e.target.value)} /></Field></div></Section>
    <Section title="Рабочая документация" description="Каждую ссылку храните отдельной записью.">{value.drawings.map(item => <div className="repeat-card" key={item.id}><Field label="Шифр"><Input value={item.code} onChange={e => patchDrawing(item.id, { code: e.target.value })} /></Field><div className="repeat-row"><Input placeholder="Лист" value={item.sheet ?? ''} onChange={e => patchDrawing(item.id, { sheet: e.target.value })} /><Input placeholder="Узел / позиция" value={item.node ?? ''} onChange={e => patchDrawing(item.id, { node: e.target.value })} /><IconButton label="Удалить ссылку" onClick={() => set('drawings', value.drawings.filter(x => x.id !== item.id))}><Trash2 /></IconButton></div></div>)}<Button onClick={addDrawing}><Plus />Добавить РД</Button></Section>
    <Section title="Нормативная документация" description="Название документа и конкретные пункты обязательны для официального PDF.">{value.ntd.map(item => <div className="repeat-card" key={item.id}><Field label="Название документа"><Input value={item.title} placeholder="СП 76.13330.2016" onChange={e => patchNtd(item.id, { title: e.target.value })} /></Field><div className="repeat-row"><Input placeholder="Пункты: 6.3.1, 6.3.2" value={item.clauses} onChange={e => patchNtd(item.id, { clauses: e.target.value })} /><IconButton label="Удалить НТД" onClick={() => set('ntd', value.ntd.filter(x => x.id !== item.id))}><Trash2 /></IconButton></div></div>)}<Button onClick={addNtd}><Plus />Добавить НТД</Button></Section>
    <Section title="Фото недостатка"><PhotoIdsPicker label="Фото недостатка" ids={value.defectPhotoIds} onChange={ids => set('defectPhotoIds', ids)} /></Section><Section title="Фото после устранения"><PhotoIdsPicker label="Фото после устранения" ids={value.resolvedPhotoIds} onChange={ids => set('resolvedPhotoIds', ids)} /></Section>
  </>;
}

const detailFields: Record<InspectionKind, Array<[string, string]>> = {
  'Операционный контроль': [['operation', 'Технологическая операция / этап'], ['parameter', 'Контролируемый параметр'], ['normative', 'Проектное / нормативное значение'], ['actual', 'Фактическое значение'], ['method', 'Способ контроля'], ['instrument', 'Применённый инструмент'], ['serial', 'Номер прибора и поверка'], ['previous', 'Предшествующие работы'], ['hidden', 'Скрываемые работы']],
  'Приёмочный контроль': [['volume', 'Предъявленный объём'], ['documentation', 'Исполнительная документация'], ['tests', 'Результаты испытаний'], ['nextReady', 'Готовность следующего этапа'], ['previousDefects', 'Ранее выданные замечания'], ['accepted', 'Принятый объём'], ['rejected', 'Непринятый объём и причина']],
  'Индивидуальные испытания': [['equipment', 'Оборудование / система'], ['serial', 'Заводской номер'], ['program', 'Программа / методика'], ['instrument', 'Прибор'], ['instrumentNumber', 'Номер прибора'], ['calibration', 'Дата окончания поверки'], ['normative', 'Нормативные параметры'], ['actual', 'Фактический результат'], ['protocol', 'Номер протокола']],
  'Комплексное опробование': [['system', 'Система'], ['program', 'Программа'], ['protocol', 'Протокол'], ['duration', 'Продолжительность'], ['participants', 'Участники']]
};

function InspectionForm({ value, onChange, onNumberBlur }: { value: Inspection; onChange: (value: Inspection) => void; onNumberBlur: () => void }) {
  const [defects, setDefects] = useState<Defect[]>([]);
  useEffect(() => { void db.defects.orderBy('updatedAt').reverse().limit(30).toArray().then(setDefects); }, [value.linkedDefectIds.length]);
  const set = <K extends keyof Inspection>(key: K, next: Inspection[K]) => onChange({ ...value, [key]: next });
  function patchStep(id: string, patch: Partial<ScenarioStep>) { set('scenarioSteps', value.scenarioSteps.map(item => item.id === id ? { ...item, ...patch } : item)); }
  async function createLinkedDefect() { const record = createDefect(await nextNumber('defects')); record.object = { ...value.object }; record.contractor = value.contractor; record.discipline = value.discipline; record.workType = value.workType; record.defectPhotoIds = [...value.photoIds]; record.description = value.description; await db.defects.add(record); set('linkedDefectIds', [...value.linkedDefectIds, record.id]); setDefects(current => [record, ...current]); }
  return <><Section title="Общие сведения"><div className="form-grid"><Field label="Номер"><Input value={value.number} onChange={e => set('number', e.target.value)} /></Field><Field label="Дата и время"><Input type="datetime-local" value={value.dateTime} onChange={e => set('dateTime', e.target.value)} /></Field><Field label="Вид контроля"><Select value={value.kind} onChange={e => set('kind', e.target.value as InspectionKind)}>{Object.keys(detailFields).map(item => <option key={item}>{item}</option>)}</Select></Field><Field label="Результат"><Select value={value.result} onChange={e => set('result', e.target.value as Inspection['result'])}><option>Принято</option><option>Принято с замечаниями</option><option>Не принято</option><option>Требуется повторное предъявление</option></Select></Field></div>{value.result === 'Требуется повторное предъявление' && <Field label="Дата повторного предъявления"><Input type="date" value={value.revisitDate ?? ''} onChange={e => set('revisitDate', e.target.value)} /></Field>}</Section>
    <Section title="Объект и участники"><div className="object-pair"><Field label="№ ГП"><Input value={value.object.gp} onChange={e => set('object', { ...value.object, gp: e.target.value })} /></Field><Field label="Название объекта"><Input value={value.object.name} onChange={e => set('object', { ...value.object, name: e.target.value })} /></Field></div><Field label="Место / оборудование"><Input value={value.location} onChange={e => set('location', e.target.value)} /></Field><div className="form-grid"><Field label="Раздел работ"><Select value={value.discipline} onChange={e => set('discipline', e.target.value)}><option value="">Выберите раздел</option>{disciplines.map(item => <option key={item}>{item}</option>)}</Select></Field><Field label="Вид работ"><Input value={value.workType} onChange={e => set('workType', e.target.value)} /></Field><Field label="Подрядчик"><Input value={value.contractor} onChange={e => set('contractor', e.target.value)} /></Field><Field label="Представитель подрядчика"><Input value={value.contractorRepresentative} onChange={e => set('contractorRepresentative', e.target.value)} /></Field></div><Field label="Инженер строительного контроля"><Input value={value.engineer} onChange={e => set('engineer', e.target.value)} /></Field><Field label="Основание проверки"><Textarea value={value.basis} onChange={e => set('basis', e.target.value)} /></Field></Section>
    <Section title={value.kind}>{detailFields[value.kind].map(([key, label]) => <Field key={key} label={label}><Textarea value={value.details[key] ?? ''} onChange={e => set('details', { ...value.details, [key]: e.target.value })} /></Field>)}</Section>
    {value.kind === 'Комплексное опробование' && <Section title="Сценарий комплексного опробования" description="Шаги выполняются в указанном порядке.">{value.scenarioSteps.map((step, index) => <div className="repeat-card scenario" key={step.id}><div className="scenario__title"><strong>Шаг {index + 1}</strong><IconButton label="Удалить шаг" onClick={() => set('scenarioSteps', value.scenarioSteps.filter(x => x.id !== step.id))}><Trash2 /></IconButton></div><Field label="Событие"><Input value={step.event} onChange={e => patchStep(step.id, { event: e.target.value })} /></Field><Field label="Команда"><Input value={step.command} onChange={e => patchStep(step.id, { command: e.target.value })} /></Field><Field label="Ожидаемый результат"><Textarea value={step.expected} onChange={e => patchStep(step.id, { expected: e.target.value })} /></Field><Field label="Фактический результат"><Textarea value={step.actual} onChange={e => patchStep(step.id, { actual: e.target.value })} /></Field><Field label="Итог"><Select value={step.result} onChange={e => patchStep(step.id, { result: e.target.value as ScenarioStep['result'] })}><option>Выполнено</option><option>Не выполнено</option><option>Не применяется</option></Select></Field></div>)}<Button onClick={() => set('scenarioSteps', [...value.scenarioSteps, { id: crypto.randomUUID(), event: '', command: '', expected: '', actual: '', result: 'Выполнено' }])}><Plus />Добавить шаг</Button></Section>}
    <Section title="Результат и фотографии"><Field label="Описание / примечание"><Textarea value={value.description} onChange={e => set('description', e.target.value)} /></Field>{value.result === 'Принято с замечаниями' && <div className="linked-defects"><strong>Связанные замечания</strong>{defects.length ? defects.map(defect => <label className="check-row" key={defect.id}><input type="checkbox" checked={value.linkedDefectIds.includes(defect.id)} onChange={e => set('linkedDefectIds', e.target.checked ? [...value.linkedDefectIds, defect.id] : value.linkedDefectIds.filter(id => id !== defect.id))} /><span>{defect.number} — {defect.description || 'черновик'}</span></label>) : <p className="section-copy">Замечаний для связи пока нет.</p>}<Button onClick={() => void createLinkedDefect()}><Plus />Создать связанное замечание</Button></div>}<PhotoIdsPicker label="Фото проверки" ids={value.photoIds} onChange={ids => set('photoIds', ids)} /></Section>
  </>;
}

function PhotoReportForm({ value, onChange, onNumberBlur, onPdf, pdfBusy }: { value: PhotoReport; onChange: (value: PhotoReport) => void; onNumberBlur: () => void; onPdf: () => void; pdfBusy: boolean }) {
  const set = <K extends keyof PhotoReport>(key: K, next: PhotoReport[K]) => onChange({ ...value, [key]: next });
  return <><Section title="Фотоотчёт"><Field label="Краткое название"><Input value={value.title} placeholder="Монтаж кабельных линий, 303 ГП" onChange={e => set('title', e.target.value)} /></Field><Field label="Общее описание"><Textarea value={value.description} onChange={e => set('description', e.target.value)} /></Field><div className="form-grid"><Field label="Дата"><Input type="date" value={value.date} onChange={e => set('date', e.target.value)} /></Field><Field label="Фото на листе"><div className="segmented small" role="radiogroup" aria-label="Количество фотографий на листе">{([1, 2, 4, 6] as const).map(count => <button type="button" role="radio" aria-checked={value.photosPerPage === count} className={value.photosPerPage === count ? 'active' : ''} key={count} onClick={() => set('photosPerPage', count)}>{count}</button>)}</div></Field></div></Section><Section title="Фотографии" description="Порядок слева направо, сверху вниз."><ReportPhotosPicker photos={value.photos} onChange={photos => set('photos', photos)} /></Section><Button className="wide-action" variant="primary" loading={pdfBusy} onClick={onPdf}><Download />Сформировать PDF</Button></>;
}
