import { useEffect, useState } from 'react';
import { Archive, Database, Download, ExternalLink, HardDrive, Upload } from 'lucide-react';
import { db } from '../db/database';
import { createBackup, downloadBlob, inspectBackup, restoreBackup, type BackupManifest } from '../services/backup';
import { formatBytes, storageEstimate } from '../services/photos';
import type { DirectoryItem } from '../types/models';
import { Button, Field, Input, Modal, Section, Select } from './ui';

export interface DisplaySettings { theme: 'system' | 'light' | 'dark'; textScale: number; bold: boolean; contrast: boolean; largeControls: boolean; reducedMotion: boolean; reducedTransparency: boolean; keepOriginals: boolean }
export const defaultDisplaySettings: DisplaySettings = { theme: 'system', textScale: 100, bold: false, contrast: false, largeControls: false, reducedMotion: false, reducedTransparency: false, keepOriginals: false };

export function applyDisplaySettings(settings: DisplaySettings): void {
  const root = document.documentElement;
  root.dataset.theme = settings.theme; root.dataset.bold = String(settings.bold); root.dataset.contrast = String(settings.contrast); root.dataset.largeControls = String(settings.largeControls); root.dataset.reducedMotion = String(settings.reducedMotion); root.dataset.reducedTransparency = String(settings.reducedTransparency); root.style.setProperty('--text-scale', String(settings.textScale / 100));
}

export function Settings({ open, onClose, onDataChanged }: { open: boolean; onClose: () => void; onDataChanged: () => void }) {
  const [settings, setSettings] = useState(defaultDisplaySettings); const [storage, setStorage] = useState<{ usage: number; quota: number; persisted?: boolean }>({ usage: 0, quota: 0, persisted: false }); const [busy, setBusy] = useState(''); const [backup, setBackup] = useState<{ file: File; manifest: BackupManifest; parsed: Awaited<ReturnType<typeof inspectBackup>> }>();
  const [directory, setDirectory] = useState<DirectoryItem[]>([]); const [newType, setNewType] = useState<DirectoryItem['type']>('contractor'); const [newValue, setNewValue] = useState('');
  useEffect(() => { if (!open) return; void db.settings.get('display').then(row => { const next = { ...defaultDisplaySettings, ...(row?.value as Partial<DisplaySettings> ?? {}) }; setSettings(next); applyDisplaySettings(next); }); void storageEstimate().then(setStorage); void db.dictionaries.orderBy('value').toArray().then(setDirectory); }, [open]);
  async function update(patch: Partial<DisplaySettings>) { const next = { ...settings, ...patch }; setSettings(next); applyDisplaySettings(next); await db.settings.put({ key: 'display', value: next }); }
  async function exportAll() { setBusy('export'); try { const blob = await createBackup(); downloadBlob(blob, `РосКапСтрой_резервная_копия_${new Date().toISOString().slice(0, 10)}.zip`); } catch (error) { alert(error instanceof Error ? error.message : 'Не удалось создать резервную копию'); } finally { setBusy(''); } }
  async function chooseBackup(file?: File) { if (!file) return; setBusy('inspect'); try { const parsed = await inspectBackup(file); setBackup({ file, manifest: parsed.manifest, parsed }); } catch (error) { alert(error instanceof Error ? error.message : 'Резервная копия повреждена'); } finally { setBusy(''); } }
  async function restore(mode: 'merge' | 'replace') { if (!backup) return; if (mode === 'replace' && !confirm('Все текущие данные будут заменены. Сначала рекомендуется сохранить резервную копию. Продолжить?')) return; setBusy('restore'); try { await restoreBackup(backup.parsed, mode); alert('Резервная копия восстановлена. Количество записей и вложений проверено.'); setBackup(undefined); onDataChanged(); } catch (error) { alert(error instanceof Error ? error.message : 'Импорт отменён. Исходные данные сохранены.'); } finally { setBusy(''); } }
  async function addDirectoryItem() { const value = newValue.trim(); if (!value) return; const item: DirectoryItem = { id: `${newType}:${value.toLocaleLowerCase('ru')}`, type: newType, value, createdAt: new Date().toISOString() }; await db.dictionaries.put(item); setDirectory(current => [...current.filter(row => row.id !== item.id), item].sort((a, b) => a.value.localeCompare(b.value, 'ru'))); setNewValue(''); }
  async function patchDirectoryItem(item: DirectoryItem, patch: Partial<DirectoryItem>) { const next = { ...item, ...patch }; await db.dictionaries.put(next); setDirectory(current => current.map(row => row.id === item.id ? next : row)); }
  async function deleteDirectoryItem(item: DirectoryItem) { if (!confirm(`Удалить из справочника «${item.value}»? В сохранённых карточках значение останется.`)) return; await db.dictionaries.delete(item.id); setDirectory(current => current.filter(row => row.id !== item.id)); }
  return <Modal open={open} title="Настройки" onClose={onClose} wide><Section title="Отображение"><div className="settings-grid"><Field label={`Размер текста — ${settings.textScale}%`}><input className="range" type="range" min="100" max="140" step="10" value={settings.textScale} onChange={e => void update({ textScale: Number(e.target.value) })} /></Field><Field label="Тема"><Select value={settings.theme} onChange={e => void update({ theme: e.target.value as DisplaySettings['theme'] })}><option value="system">Системная</option><option value="light">Светлая</option><option value="dark">Тёмная</option></Select></Field></div><div className="toggle-list">{([['bold', 'Жирный текст'], ['contrast', 'Высокая контрастность'], ['largeControls', 'Увеличенные кнопки'], ['reducedMotion', 'Уменьшение движения'], ['reducedTransparency', 'Уменьшение прозрачности'], ['keepOriginals', 'Хранить оригиналы фотографий']] as const).map(([key, label]) => <label className="toggle" key={key}><span>{label}</span><input type="checkbox" checked={settings[key]} onChange={e => void update({ [key]: e.target.checked })} /></label>)}</div></Section>
    <Section title="Данные"><div className="storage-card"><HardDrive /><div><strong>{formatBytes(storage.usage)} занято</strong><span>{storage.quota ? `из ${formatBytes(storage.quota)}` : 'Квота браузера недоступна'}{storage.persisted ? ' • постоянное хранение' : ''}</span></div></div><div className="data-actions"><Button loading={busy === 'export'} onClick={() => void exportAll()}><Download />Экспорт всех данных</Button><label className="button button--secondary"><Upload />Импорт резервной копии<Input hidden type="file" accept=".zip,application/zip" onChange={e => void chooseBackup(e.target.files?.[0])} /></label></div><p className="security-note"><Archive />ZIP содержит рабочие данные и фотографии без шифрования. Храните его в защищённом месте.</p>{backup && <div className="backup-preview"><strong>{backup.file.name}</strong><span>Создана {new Date(backup.manifest.createdAt).toLocaleString('ru-RU')}</span><span>{backup.manifest.counts.defects ?? 0} замечаний • {backup.manifest.counts.inspections ?? 0} проверок • {backup.manifest.counts.photoReports ?? 0} фотоотчётов • {backup.manifest.counts.attachments ?? 0} вложений</span><div><Button loading={busy === 'restore'} onClick={() => void restore('merge')}>Объединить</Button><Button variant="danger" loading={busy === 'restore'} onClick={() => void restore('replace')}>Заменить всё</Button></div></div>}</Section>
    <Section title="Справочники"><p className="section-copy">Объекты и подрядчики пополняются из карточек. Удаление значения не меняет уже сохранённые документы.</p><div className="directory-add"><Select aria-label="Тип справочника" value={newType} onChange={e => setNewType(e.target.value as DirectoryItem['type'])}><option value="object">Объект</option><option value="contractor">Подрядчик</option><option value="discipline">Раздел работ</option><option value="workType">Вид работ</option></Select><Input value={newValue} placeholder="Новое значение" onChange={e => setNewValue(e.target.value)} /><Button onClick={() => void addDirectoryItem()}><Database />Добавить</Button></div><div className="directory-list">{directory.map(item => <div className="directory-row" key={item.id}><Input aria-label={`Значение ${item.value}`} value={item.value} onChange={e => void patchDirectoryItem(item, { value: e.target.value })} /><label><input type="checkbox" checked={Boolean(item.hidden)} onChange={e => void patchDirectoryItem(item, { hidden: e.target.checked })} /> Скрыто</label><Button variant="ghost" onClick={() => void deleteDirectoryItem(item)}>Удалить</Button></div>)}</div></Section>
    <Section title="О приложении"><div className="about"><strong>РосКапСтрой</strong><span>Версия V2.0</span><span>Разработчик ПО</span><b>Святослав Щипин</b><a href="https://t.me/w40jvgg" target="_blank" rel="noreferrer">Telegram @w40jvgg <ExternalLink /></a></div></Section>
  </Modal>;
}
